const { test,after } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID } = require('crypto');
const fs = require('fs/promises');
const path = require('path');
const express = require('express');
const jwt = require('jsonwebtoken');
const db = require('../config/db');
const businessRoutes = require('../routes/businessRoutes');
const transactionRoutes = require('../routes/transactionRoutes');
const { cleanupEvidence,evidenceDir,removeEvidence } = require('../services/evidenceService');
const { vietnamDate } = require('../utils/businessDate');
after(() => db.close());
test('employee submissions require approval, evidence is private and expires, automatic approval applies only to new entries', { skip: process.env.RUN_DB_TESTS !== '1' },async () => {
  const users=[]; const businesses=[]; const filenames=[]; let server;
  const suffix=randomUUID().slice(0,10);
  const secret=process.env.JWT_SECRET || 'test-secret-that-is-longer-than-32-characters'; process.env.JWT_SECRET=secret;
  try {
    for (const role of ['owner','employee','employee','owner']) users.push((await db.query('INSERT INTO users(name,email,password_hash,role) VALUES ($1,$2,$3,$4) RETURNING id', ['Approval test',`${users.length}-${suffix}@example.invalid`,'invalid-test-hash',role])).rows[0].id);
    for (const owner of [users[0],users[3]]) businesses.push((await db.query("INSERT INTO businesses(owner_id,business_code,model,name) VALUES ($1,$2,'Quán cafe','Approval test') RETURNING id", [owner,`APR-${businesses.length}-${suffix}`])).rows[0].id);
    for (const user of [users[1],users[2]]) await db.query('INSERT INTO employees(business_id,user_id,employee_code,name) VALUES ($1,$2,$3,$4)', [businesses[0],user,user,'Approval test']);
    const app=express(); app.use(express.json()); app.use('/api/business',businessRoutes); app.use('/api/transactions',transactionRoutes);
    app.use((error,req,res,next) => res.status(error.code?.startsWith('LIMIT_') ? 400 : 500).json({ message: 'Request failed' }));
    server=await new Promise(resolve => { const instance=app.listen(0,'127.0.0.1',() => resolve(instance)); });
    const call=async (user,method,resource,body) => {
      const multipart=body instanceof FormData;
      const response=await fetch(`http://127.0.0.1:${server.address().port}${resource}`, { method,headers: { Authorization: `Bearer ${jwt.sign({ userId: user },secret)}`,...(multipart ? {} : { 'Content-Type':'application/json' }) },body: body === undefined ? undefined : multipart ? body : JSON.stringify(body) });
      const data=response.headers.get('content-type')?.startsWith('image/') ? Buffer.from(await response.arrayBuffer()) : await response.json();
      return { status:response.status,body:data };
    };
    const payload=(amount,type='INCOME') => ({ scope:'business',amount,type,category:'Integration approval',date:vietnamDate(),paymentMethod:'CASH',requestId:randomUUID() });
    const upload=(input,bytes) => { const data=new FormData(); Object.entries(input).forEach(([key,value]) => data.append(key,value)); data.append('evidence',new Blob([bytes],{ type:'image/png' }),'proof.png'); return data; };
    const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6N9kAAAAASUVORK5CYII=','base64');
    const request=payload(12000);
    const created=await call(users[1],'POST','/api/transactions',upload({ ...request,approval_status:'APPROVED' },png));
    assert.equal(created.status,201); assert.equal(created.body.approval_status,'PENDING'); assert.equal(created.body.has_evidence,true); assert.equal(created.body.evidence_filename,undefined);
    const id=created.body.id;
    const filename=(await db.query('SELECT evidence_filename FROM transactions WHERE id=$1',[id])).rows[0].evidence_filename; filenames.push(filename);
    assert.equal((await call(users[0],'GET',`/api/business/evidence/${id}`)).status,200);
    assert.equal((await call(users[1],'GET',`/api/business/evidence/${id}`)).status,200);
    assert.equal((await call(users[2],'GET',`/api/business/evidence/${id}`)).status,404);
    assert.equal((await call(users[3],'GET',`/api/business/evidence/${id}`)).status,404);
    const summary=async () => (await call(users[0],'GET','/api/transactions/summary?scope=business')).body;
    assert.equal(Number((await summary()).today_income),0);
    assert.equal((await call(users[1],'PUT',`/api/transactions/${id}`,{ amount:1 })).status,403);
    assert.equal((await call(users[1],'DELETE',`/api/transactions/${id}`)).status,403);
    assert.equal((await call(users[1],'POST',`/api/business/approvals/${id}`,{ decision:'APPROVED' })).status,403);
    assert.equal((await call(users[3],'POST',`/api/business/approvals/${id}`,{ decision:'APPROVED' })).status,404);
    const replay=await call(users[1],'POST','/api/transactions',upload(request,png)); assert.equal(replay.status,200); assert.equal(replay.body.id,id);
    const reviews=await Promise.all(Array.from({ length:3 },() => call(users[0],'POST',`/api/business/approvals/${id}`,{ decision:'APPROVED' })));
    assert.ok(reviews.every(result => result.status===200)); assert.equal(Number((await summary()).today_income),12000);
    assert.equal((await call(users[0],'POST',`/api/business/approvals/${id}`,{ decision:'REJECTED' })).status,409);
    const expense=await call(users[1],'POST','/api/transactions',payload(3000,'EXPENSE'));
    assert.equal(expense.body.approval_status,'PENDING');
    assert.equal((await call(users[0],'POST',`/api/business/approvals/${expense.body.id}`,{ decision:'REJECTED' })).status,200);
    assert.equal(Number((await summary()).today_expense),0);
    const waiting=await call(users[1],'POST','/api/transactions',payload(1000));
    assert.equal((await call(users[1],'PUT','/api/business/approval-settings',{ autoApprove:true })).status,403);
    assert.equal((await call(users[0],'PUT','/api/business/approval-settings',{ autoApprove:true })).status,200);
    assert.equal((await db.query('SELECT approval_status FROM transactions WHERE id=$1',[waiting.body.id])).rows[0].approval_status,'PENDING');
    const automatic=await call(users[1],'POST','/api/transactions',payload(5000,'EXPENSE')); assert.equal(automatic.body.approval_status,'APPROVED'); assert.equal(Number((await summary()).today_expense),5000);
    const ownerEntry=await call(users[0],'POST','/api/transactions',payload(2000)); assert.equal(ownerEntry.body.approval_status,'APPROVED');
    await call(users[0],'PUT','/api/business/approval-settings',{ autoApprove:false });
    const product=(await db.query("INSERT INTO products(business_id,name,price,track_stock) VALUES ($1,'Approval POS',1000,false) RETURNING id",[businesses[0]])).rows[0].id;
    const sale=await call(users[1],'POST','/api/business/checkout',{ items:[{ productId:product,quantity:1 }],requestId:randomUUID(),paymentMethod:'CASH' });
    assert.equal(sale.status,201); assert.equal(sale.body.transaction.approval_status,'PENDING');
    assert.equal(Number((await summary()).today_income),14000);
    const [year,month]=vietnamDate().split('-');
    const calendarPath=`/api/business/calendar?month=${Number(month)}&year=${year}`;
    assert.equal((await call(users[1],'GET',calendarPath)).status,403);
    assert.equal((await call(users[3],'GET',`${calendarPath}&businessId=${businesses[0]}`)).status,403);
    assert.equal((await call(users[0],'GET','/api/business/calendar?month=13&year=2026')).status,400);
    const calendar=await call(users[0],'GET',calendarPath);
    assert.equal(calendar.status,200);
    const daily=calendar.body.days.find(row => row.date.slice(0,10)===vietnamDate());
    assert.equal(Number(daily.income),14000); assert.equal(Number(daily.expense),5000);
    const dayDetails=await call(users[0],'GET',`/api/transactions?scope=business&date=${vietnamDate()}&limit=50`);
    assert.equal(dayDetails.status,200); assert.equal(dayDetails.body.length,3);
    assert.ok(dayDetails.body.every(row => row.approval_status==='APPROVED' && row.date.slice(0,10)===vietnamDate()));
    assert.equal((await call(users[0],'GET','/api/transactions?scope=business&date=1999-01-01')).body.length,0);
    assert.equal((await call(users[0],'GET','/api/transactions?scope=business&date=2026-02-30')).status,400);
    assert.equal((await call(users[0],'POST','/api/transactions',upload(payload(1),png))).status,400);
    assert.equal((await call(users[1],'POST','/api/transactions',upload(payload(1),Buffer.from('not an image')))).status,400);
    await db.query("UPDATE transactions SET evidence_expires_at=now()-interval '1 second' WHERE id=$1",[id]);
    await db.query("UPDATE transaction_evidence_files SET expires_at=now()-interval '1 second' WHERE filename=$1",[filename]);
    assert.equal((await call(users[0],'GET',`/api/business/evidence/${id}`)).status,404);
    await cleanupEvidence();
    await assert.rejects(fs.stat(path.join(evidenceDir,filename)),{ code:'ENOENT' });
    assert.equal((await db.query('SELECT evidence_filename FROM transactions WHERE id=$1',[id])).rows[0].evidence_filename,null);
    assert.equal(Number((await summary()).today_income),14000);
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    for (const filename of filenames) await removeEvidence(filename);
    await db.query('DELETE FROM sale_items WHERE transaction_id IN (SELECT id FROM transactions WHERE business_id=ANY($1::int[]))',[businesses]);
    await db.query('DELETE FROM transactions WHERE business_id=ANY($1::int[])',[businesses]);
    await db.query('DELETE FROM businesses WHERE id=ANY($1::int[])',[businesses]);
    await db.query('DELETE FROM users WHERE id=ANY($1::int[])',[users]);
  }
});
