const { test, after } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID, randomBytes, createHmac } = require('crypto');
const express = require('express');
const jwt = require('jsonwebtoken');
const db = require('../config/db');
const bank = require('../controllers/bankController');
const { vietnamDate } = require('../utils/businessDate');
after(() => db.close());

test('SePay verifies money exactly once, isolates businesses, protects revenue and keeps tables open until paid', { skip: process.env.RUN_DB_TESTS !== '1' }, async () => {
  const users = [], businesses = []; let server;
  const suffix = randomUUID().slice(0, 10);
  const jwtSecret = process.env.JWT_SECRET || randomBytes(40).toString('hex');
  process.env.JWT_SECRET = jwtSecret;
  process.env.PAYMENT_SECRET_KEY = randomBytes(32).toString('hex');
  process.env.PAYMENT_PUBLIC_URL = 'https://bank-test.example.invalid';
  try {
    for (const role of ['owner', 'employee', 'owner']) users.push((await db.query('INSERT INTO users(name,email,password_hash,role) VALUES ($1,$2,$3,$4) RETURNING id', ['Bank test', `${users.length}-${suffix}@example.invalid`, 'invalid-test-hash', role])).rows[0].id);
    for (const owner of [users[0], users[2]]) businesses.push((await db.query("INSERT INTO businesses(owner_id,business_code,model,name,auto_approve_transactions) VALUES ($1,$2,'Quán cafe','Bank test',true) RETURNING id", [owner, `BANK-${businesses.length}-${suffix}`])).rows[0].id);
    await db.query("INSERT INTO employees(business_id,user_id,employee_code,name) VALUES ($1,$2,1,'Bank test')", [businesses[0], users[1]]);
    const app = express(); app.set('trust proxy', 'loopback');
    app.post('/api/payments/sepay/:id', express.raw({ type: 'application/json', limit: '32kb' }), bank.webhook);
    app.use(express.json()); app.use('/api/payments', require('../routes/paymentRoutes'));
    app.use('/api/business', require('../routes/businessRoutes')); app.use('/api/transactions', require('../routes/transactionRoutes'));
    app.use((error, req, res, next) => res.status(error.status || 500).json({ message: 'Test request failed', code: error.code }));
    server = await new Promise(resolve => { const instance = app.listen(0, '127.0.0.1', () => resolve(instance)); });
    const root = `http://127.0.0.1:${server.address().port}`;
    const call = async (user, method, path, body, secure = true) => {
      const response = await fetch(`${root}${path}`, { method, headers: { Authorization: `Bearer ${jwt.sign({ userId: user }, jwtSecret)}`, 'Content-Type': 'application/json', ...(secure ? { 'X-Forwarded-Proto': 'https' } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
      return { status: response.status, body: await response.json() };
    };
    const account = String(Date.now());
    const connectionInput = { bank: 'MBBank', accountNumber: account, accountName: 'Bank test', enabled: true, confirmedLiveConnection: true };
    assert.equal((await call(users[0], 'PUT', '/api/payments/connection', connectionInput, false)).status, 503);
    assert.equal((await call(users[1], 'PUT', '/api/payments/connection', connectionInput)).status, 403);
    const configured = await call(users[0], 'PUT', '/api/payments/connection', connectionInput);
    assert.equal(configured.status, 200); assert.ok(configured.body.webhookSecret);
    const connection = configured.body.connection, webhookSecret = configured.body.webhookSecret;
    assert.equal((await call(users[0], 'GET', '/api/payments/connection')).body.webhookSecret, undefined);
    const product = (await db.query("INSERT INTO products(business_id,name,price,track_stock,stock_quantity) VALUES ($1,'Bank POS',7500,true,20) RETURNING id", [businesses[0]])).rows[0].id;
    const saleInput = { items: [{ productId: product, quantity: 1 }], requestId: randomUUID(), paymentMethod: 'TRANSFER' };
    const sale = await call(users[1], 'POST', '/api/business/checkout', saleInput);
    assert.equal(sale.status, 201); assert.equal(sale.body.transaction.bank_payment_status, 'WAITING');
    const payment = sale.body.bankPayment; assert.ok(payment.qrUrl);
    const replay = await call(users[1], 'POST', '/api/business/checkout', saleInput);
    assert.equal(replay.body.bankPayment.id, payment.id);
    assert.equal(Number((await db.query('SELECT stock_quantity FROM products WHERE id=$1', [product])).rows[0].stock_quantity), 19);
    const income = async () => Number((await call(users[0], 'GET', '/api/transactions/summary?scope=business')).body.today_income);
    assert.equal(await income(), 0);
    assert.equal((await call(users[2], 'GET', `/api/payments/intents/${payment.id}`)).status, 404);
    assert.equal((await call(users[1], 'GET', '/api/payments/events')).status, 403);
    assert.equal((await call(users[0], 'PUT', `/api/transactions/${sale.body.transaction.id}`, { amount: 1 })).status, 404);
    assert.equal((await call(users[0], 'PUT', '/api/payments/connection', { ...connectionInput, enabled: false })).status, 409);
    let providerId = 1;
    const notify = async (intent, overrides = {}, invalid = false, secure = true) => {
      const date = new Date().toLocaleString('sv-SE', { timeZone: 'Asia/Ho_Chi_Minh' });
      const body = { id: providerId++, gateway: 'MBBank', transactionDate: date, accountNumber: account, transferType: 'in', transferAmount: intent.amount, content: intent.code, referenceCode: 'test', ...overrides };
      const raw = JSON.stringify(body), timestamp = String(Math.floor(Date.now() / 1000));
      const signature = `sha256=${createHmac('sha256', invalid ? 'invalid' : webhookSecret).update(`${timestamp}.${raw}`).digest('hex')}`;
      const response = await fetch(`${root}/api/payments/sepay/${connection.id}`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-SePay-Timestamp': timestamp, 'X-SePay-Signature': signature, ...(secure ? { 'X-Forwarded-Proto': 'https' } : {}) }, body: raw });
      return { status: response.status, body: await response.json() };
    };
    assert.equal((await notify(payment, {}, true)).status, 401);
    assert.equal((await notify(payment, {}, false, false)).status, 503);
    assert.equal((await notify(payment, { transferAmount: 1 })).status, 200); assert.equal(await income(), 0);
    await notify(payment, { accountNumber: '123456789' }); assert.equal(await income(), 0);
    await notify(payment, { transferType: 'out' }); assert.equal(await income(), 0);
    const confirmations = await Promise.all(Array.from({ length: 3 }, () => notify(payment, { id: 100 })));
    assert.ok(confirmations.every(result => result.status === 200)); assert.equal(await income(), 7500);
    await notify(payment, { id: 101 }); assert.equal(await income(), 7500);
    assert.equal((await call(users[1], 'POST', `/api/payments/intents/${payment.id}/cancel`, {})).status, 409);
    assert.equal((await call(users[0], 'DELETE', `/api/transactions/${sale.body.transaction.id}`)).status, 404);
    const table = (await call(users[0], 'POST', '/api/business/tables', { name: 'Bank table', surchargeEnabled: true, hourlyRate: 15000, billingUnit: 'MINUTE' })).body.table;
    const path = `/api/business/tables/${table.id}`;
    await call(users[1], 'PATCH', `${path}/occupancy`, { isOccupied: true, version: 0 });
    const quote = (await call(users[1], 'POST', `${path}/quote`, { version: 1 })).body.quote;
    const tableInput = { sessionId: quote.sessionId, quoteToken: quote.quoteToken, paymentMethod: 'TRANSFER' };
    const tablePayment = await call(users[1], 'POST', `${path}/pay`, tableInput);
    assert.equal(tablePayment.status, 200); assert.equal(tablePayment.body.table.is_occupied, true); assert.ok(tablePayment.body.bankPayment);
    assert.equal((await call(users[1], 'POST', `${path}/pay`, { ...tableInput, paymentMethod: 'CASH' })).status, 409);
    assert.equal((await call(users[0], 'POST', `${path}/quote`, { version: 1 })).body.quote.bankPayment.id, tablePayment.body.bankPayment.id);
    await notify(tablePayment.body.bankPayment);
    assert.equal((await call(users[0], 'GET', '/api/business/tables')).body.tables.find(item => item.id === table.id).is_occupied, false);
    const submissionInput = { scope: 'business', type: 'INCOME', amount: 1000, category: 'Test', date: vietnamDate(), paymentMethod: 'TRANSFER', requestId: randomUUID(), bank_payment_status: 'VERIFIED' };
    const submission = await call(users[1], 'POST', '/api/transactions', submissionInput);
    assert.equal(submission.status, 201); assert.equal(submission.body.bank_payment_status, 'WAITING');
    assert.equal((await call(users[1], 'POST', '/api/transactions', submissionInput)).body.bankPayment.id, submission.body.bankPayment.id);
    await notify(submission.body.bankPayment, { content: 'No payment code' });
    const event = (await call(users[0], 'GET', '/api/payments/events')).body.events.find(item => item.status === 'UNMATCHED');
    assert.ok(event);
    assert.equal((await call(users[1], 'POST', `/api/payments/events/${event.id}/reconcile`, { intentId: submission.body.bankPayment.id })).status, 403);
    assert.equal((await call(users[2], 'POST', `/api/payments/events/${event.id}/reconcile`, { intentId: submission.body.bankPayment.id })).status, 404);
    assert.equal((await call(users[0], 'POST', `/api/payments/events/${event.id}/reconcile`, { intentId: submission.body.bankPayment.id })).status, 200);
    const cancelled = await call(users[1], 'POST', '/api/transactions', { ...submissionInput, requestId: randomUUID() });
    const beforeCancel = await income();
    assert.equal((await call(users[1], 'POST', `/api/payments/intents/${cancelled.body.bankPayment.id}/cancel`, {})).status, 200);
    await notify(cancelled.body.bankPayment); assert.equal(await income(), beforeCancel);
  } finally {
    if (server) await new Promise(resolve => server.close(resolve));
    if (businesses.length) {
      await db.query('DELETE FROM bank_events WHERE business_id=ANY($1::int[])', [businesses]);
      await db.query('DELETE FROM bank_payment_intents WHERE business_id=ANY($1::int[])', [businesses]);
      await db.query('DELETE FROM bank_connections WHERE business_id=ANY($1::int[])', [businesses]);
      await db.query('DELETE FROM stock_movements WHERE business_id=ANY($1::int[])', [businesses]);
      await db.query('DELETE FROM sale_items WHERE transaction_id IN (SELECT id FROM transactions WHERE business_id=ANY($1::int[]))', [businesses]);
      await db.query('DELETE FROM transactions WHERE business_id=ANY($1::int[])', [businesses]);
      await db.query('DELETE FROM business_daily_totals WHERE business_id=ANY($1::int[])', [businesses]);
      await db.query('DELETE FROM businesses WHERE id=ANY($1::int[])', [businesses]);
    }
    if (users.length) await db.query('DELETE FROM users WHERE id=ANY($1::int[])', [users]);
  }
});
