const {randomInt}=require('crypto');
const roles={villager:{name:'Dân ngu',description:'Thảo luận và bỏ phiếu tìm Sói vào ban ngày.'},wolf:{name:'Sói ngu',description:'Cùng bầy chọn một người để cắn mỗi đêm.'},cursedWolf:{name:'Sói nguyền',description:'Sau lượt bầy Sói, chọn một người khác để biến thành Sói. Một lần mỗi ván, độc lập với lượt giết.'},cupid:{name:'Cupid',description:'Bắt buộc ghép đôi đêm đầu, trước Sói nguyền. Một người chết, người kia chết theo.'},witch:{name:'Phù thủy',description:'Một bình cứu và một bình độc cho cả ván. Mỗi đêm chỉ dùng một bình.'},seer:{name:'Tiên tri',description:'Mỗi đêm xem một người có thuộc phe Sói hay không.'},guard:{name:'Bảo vệ',description:'Bảo vệ một người mỗi đêm, không chọn cùng người hai đêm liên tiếp.'}};
roles.hunter={name:'Thợ săn',description:'Khi chết trong đêm hoặc sau bỏ phiếu, chọn một người còn sống chết cùng. Chỉ bắn một lần. Thắng cùng phe Dân.'};
const defaultDeck={wolf:1,cursedWolf:0,cupid:0,witch:0,seer:1,guard:0,hunter:0};
const timerDefaults={cupid:30,curse:20,night:60,guard:30,seer:30,witch:30,hunter:30,day:120,vote:60};
function configure(s,id,deck,timers,revealDeadRoles){if(id!==s.host)fail('Chỉ chủ phòng được cài đặt.',403);if(!['lobby','ended'].includes(s.phase))fail('Không đổi bộ thẻ khi ván đang diễn ra.');const result={};for(const key of Object.keys(defaultDeck)){const n=deck?.[key];if(!Number.isInteger(n)||n<0||n>(key==='wolf'?s.settings.capacity:1))fail('Số lượng thẻ không hợp lệ.');result[key]=n;}if(result.wolf+result.cursedWolf<1)fail('Cần ít nhất một Sói ngu hoặc Sói nguyền.');if(result.wolf+result.cursedWolf>=s.settings.capacity)fail('Cần có phe Dân.');const durations={};if(timers!==undefined){for(const key of Object.keys(timerDefaults)){const n=timers[key];if(!Number.isInteger(n)||n<10||n>900)fail('Thời gian phải là số giây từ 10 đến 900.');durations[key]=n;}}if(revealDeadRoles!==undefined&&typeof revealDeadRoles!=='boolean')fail('Cài đặt lộ vai trò không hợp lệ.');Object.assign(s.settings,durations);if(revealDeadRoles!==undefined)s.settings.revealDeadRoles=revealDeadRoles;s.settings.deck=result;s.players.forEach(p=>p.ready=false);}
const isWolf=p=>['wolf','cursedWolf'].includes(p.role);
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
const member=(s,id)=>{const p=s.players.find(p=>p.id===id);if(!p)fail('Bạn không ở trong phòng.',403);return p;};
function log(s,message,now){s.log.push({id:s.log.length?s.log.at(-1).id+1:1,message,at:now});s.log=s.log.slice(-200);}
function create(host,name,settings={}){return {name,host:host.id,phase:'lobby',phaseId:0,round:0,day:0,deadline:null,winner:null,settings:{...timerDefaults,revealDeadRoles:true,capacity:14,deck:{...defaultDeck},public:settings.public===true,mode:settings.mode==='3d'?'3d':'2d'},players:[{id:host.id,name:host.name,ready:false,alive:true,voiceUntil:0}],actions:{},knowledge:{},chat:[],log:[]};}
function winner(s){const alive=s.players.filter(p=>p.alive),wolves=alive.filter(isWolf).length;if(alive.length===0)return 'draw';if(alive.length===2&&s.lovers?.includes(alive[0].id)&&s.lovers.includes(alive[1].id)&&wolves===1)return 'lovers';return wolves===0?'village':wolves>=alive.length-wolves?'wolves':null;}
function hasCalledRole(s,role){return s.players.some(p=>p.alive&&(p.role===role||p.originalRole===role));}
function phase(s,next,now){s.phase=next;s.phaseId++;s.actions={};s.deadline=next==='ended'||next==='lobby'?null:now+(s.settings[next]??60)*1000;s.autoSkipAt=null;s.autoSkipDisplayDeadline=null;const role={guard:'guard',seer:'seer',witch:'witch'}[next];if(role&&hasCalledRole(s,role)&&!s.players.some(p=>p.alive&&p.role===role)){s.autoSkipDisplayDeadline=s.deadline;s.autoSkipAt=now+5000;s.deadline=now+8000;s.autoSkippedRole=role;}else s.autoSkippedRole=null;}
function endIfWon(s,now){if(s.hunterQueue?.length)return false;s.winner=winner(s);if(s.winner){phase(s,'ended',now);log(s,s.winner==='village'?'Dân làng chiến thắng!':s.winner==='lovers'?'Cặp đôi khác phe chiến thắng!':s.winner==='draw'?'Ván hòa.':'Bầy Sói chiến thắng!',now);return true;}return false;}
function eliminate(s,id,reason,now){const p=member(s,id);if(!p.alive)return;p.alive=false;if(p.role==='hunter'&&s.collectHunter&&!p.hunterUsed){s.hunterQueue??=[];if(!s.hunterQueue.includes(id))s.hunterQueue.push(id);}log(s,p.name+' '+reason,now);if(s.lovers?.includes(id)){const other=s.lovers.find(x=>x!==id);if(other)eliminate(s,other,'chết theo người yêu.',now);}}
function callCurse(s,now){s.pendingCurse=null;phase(s,'night',now);}
function resumeAfterDeath(s,now){if(s.hunterQueue?.length){phase(s,'hunter',now);return;}if(endIfWon(s,now))return;if(s.afterHunter==='day'){phase(s,'day',now);log(s,'Ngày '+s.day+': cùng thảo luận để tìm Sói.',now);}else{s.day++;if(s.day>30){s.winner='draw';phase(s,'ended',now);}else callCurse(s,now);}}
function afterGuard(s,now){const cursed=s.players.find(p=>p.alive&&p.role==='cursedWolf');if(hasCalledRole(s,'seer'))phase(s,'seer',now);else afterSeer(s,now);}
function afterSeer(s,now){if(hasCalledRole(s,'witch'))phase(s,'witch',now);else finishNight(s,now);}
function finishNight(s,now){s.collectHunter=true;const witch=s.players.find(p=>p.alive&&p.role==='witch'),a=witch?s.actions[witch.id]:null;if(s.pendingVictim!==null&&!a?.save)eliminate(s,s.pendingVictim,'đã bị loại trong đêm.',now);else log(s,'Không ai chết vì vết cắn của Sói đêm qua.',now);if(a?.poison!==null&&a?.poison!==undefined)eliminate(s,a.poison,'bị loại bởi bình độc.',now);s.pendingVictim=null;s.collectHunter=false;s.afterHunter='day';resumeAfterDeath(s,now);}
function plurality(values,includeSkip=false){const counts=new Map();for(const value of values)if(value!==null||includeSkip)counts.set(value,(counts.get(value)||0)+1);const ranked=[...counts].sort((a,b)=>b[1]-a[1]);return ranked.length&&(!ranked[1]||ranked[0][1]>ranked[1][1])?ranked[0][0]:null;}
function start(s,id,now=Date.now()){
 if(id!==s.host)fail('Chỉ chủ phòng được bắt đầu.',403);if(!['lobby','ended'].includes(s.phase))fail('Ván đang diễn ra.');
 if(s.players.length<5)fail('Cần ít nhất 5 người.');if(s.players.some(p=>p.id!==s.host&&!p.ready))fail('Những người chơi khác cần sẵn sàng.');
 const deck=s.settings.deck||defaultDeck,cards=Object.entries(deck).flatMap(([role,n])=>Array(n).fill(role));if(cards.length>s.players.length)fail('Tổng thẻ đã chọn vượt số người trong phòng.');if(deck.wolf+deck.cursedWolf<1||deck.wolf+deck.cursedWolf>=s.players.length-(deck.wolf+deck.cursedWolf))fail('Cần ít nhất một Sói và số Sói phải ít hơn phe Dân khi bắt đầu.');while(cards.length<s.players.length)cards.push('villager');
 for(let i=cards.length-1;i>0;i--){const j=randomInt(i+1);[cards[i],cards[j]]=[cards[j],cards[i]];}
 s.announcements=[];s.nextAfterAnnouncement=null;s.players.forEach((p,i)=>{p.role=cards[i];p.alive=true;p.ready=false;p.previousGuard=null;p.hunterUsed=false;p.originalRole=null;p.cursedDay=null;});s.round++;s.day=1;s.knowledge={};s.chat=[];s.log=[];s.winner=null;s.lovers=[];s.curseUsed=false;s.curseTonight=false;s.potions={save:true,poison:true};s.pendingVictim=null;s.hunterQueue=[];s.collectHunter=false;for(const [key,value] of Object.entries(timerDefaults))s.settings[key]??=value;s.settings.reveal=15;phase(s,'reveal',now);log(s,'Bạn có 15 giây xem thẻ vai trò trước khi đêm đầu bắt đầu.',now);
}
function advanceCore(s,now=Date.now()){
 if(!s.deadline||now<s.deadline)return false;
 // Only one phase per tick: reconnection never skips players' opportunity to act.
 if(s.phase==='reveal'){if(s.players.some(p=>p.alive&&p.role==='cupid'))phase(s,'cupid',now);else callCurse(s,now);
 }else if(s.phase==='cupid'){
  if(!s.lovers.length){const ids=s.players.filter(p=>p.alive).map(p=>p.id);const first=ids.splice(randomInt(ids.length),1)[0];s.lovers=[first,ids[randomInt(ids.length)]];}
  callCurse(s,now);
 }else if(s.phase==='curse'){if(s.pendingCurse!=null&&!s.curseUsed){const target=member(s,s.pendingCurse);target.originalRole??=target.role;target.role='wolf';target.cursedDay=s.day;s.curseUsed=true;}s.pendingCurse=null;if(hasCalledRole(s,'guard'))phase(s,'guard',now);else afterGuard(s,now);}
 else if(s.phase==='night'){
  s.pendingVictim=plurality(s.players.filter(p=>p.alive&&isWolf(p)).map(p=>s.actions[p.id]?.target??null));if(s.players.some(p=>p.alive&&p.role==='cursedWolf'))phase(s,'curse',now);else if(hasCalledRole(s,'guard'))phase(s,'guard',now);else afterGuard(s,now);
 }else if(s.phase==='guard'){const guard=s.players.find(p=>p.alive&&p.role==='guard'),target=guard?s.actions[guard.id]?.target:null;if(guard)guard.previousGuard=target??null;if(target!==null&&target!==undefined&&target===s.pendingVictim)s.pendingVictim=null;afterGuard(s,now);
 }else if(s.phase==='seer')afterSeer(s,now);
 else if(s.phase==='hunter'){const id=s.hunterQueue.shift(),target=s.actions[id]?.target;member(s,id).hunterUsed=true;s.collectHunter=true;if(target!==null&&target!==undefined)eliminate(s,target,'bị Thợ săn bắn.',now);s.collectHunter=false;resumeAfterDeath(s,now);
 }else if(s.phase==='witch')finishNight(s,now);
 else if(s.phase==='day'){phase(s,'vote',now);log(s,'Bắt đầu bỏ phiếu. Phiếu hòa hoặc không có phiếu sẽ không loại ai.',now);}
 else if(s.phase==='vote'){
  s.collectHunter=true;const target=plurality(Object.values(s.actions).map(a=>a.target),true);if(target!==null)eliminate(s,target,'bị loại sau bỏ phiếu.',now);else log(s,'Không có người bị loại sau bỏ phiếu.',now);
  s.collectHunter=false;s.afterHunter='night';resumeAfterDeath(s,now);
 }return true;
}
function announceUpdates(s,previousLogId,now){const entries=s.log.filter(e=>e.id>previousLogId);if(!entries.length)return;const next={phase:s.phase,duration:s.deadline===null?null:s.deadline-now,autoSkippedRole:s.autoSkippedRole,autoSkipDelay:s.autoSkipAt?Math.max(0,s.autoSkipAt-now):null,autoSkipDisplayDuration:s.autoSkipDisplayDeadline?s.autoSkipDisplayDeadline-now:null};let at=now;s.announcements=entries.map(entry=>{const duration=Math.min(6500,Math.max(3800,1800+entry.message.length*45));const item={id:entry.id,message:entry.message,start:at,end:at+duration};at+=duration;return item;});s.nextAfterAnnouncement=next;s.phase='announcement';s.phaseId++;s.actions={};s.deadline=at;s.autoSkipAt=null;s.autoSkipDisplayDeadline=null;s.autoSkippedRole=null;}
function advance(s,now=Date.now()){if(s.phase==='announcement'){if(now<s.deadline)return false;const next=s.nextAfterAnnouncement;phase(s,next.phase,now);s.deadline=next.duration===null?null:now+next.duration;s.autoSkippedRole=next.autoSkippedRole;s.autoSkipAt=next.autoSkipDelay===null?null:now+next.autoSkipDelay;s.autoSkipDisplayDeadline=next.autoSkipDisplayDuration===null?null:now+next.autoSkipDisplayDuration;s.announcements=[];s.nextAfterAnnouncement=null;return true;}const last=s.log.at(-1)?.id||0,result=advanceCore(s,now);if(result)announceUpdates(s,last,now);return result;}
function shortenWhenComplete(s,now){let actors=[];if(['vote','day'].includes(s.phase))actors=s.players.filter(p=>p.alive);else if(s.phase==='night')actors=s.players.filter(p=>p.alive&&isWolf(p));else if(s.phase==='hunter')actors=s.players.filter(p=>p.id===s.hunterQueue?.[0]);else {const role={cupid:'cupid',curse:'cursedWolf',guard:'guard',seer:'seer',witch:'witch'}[s.phase];if(role)actors=s.players.filter(p=>p.alive&&p.role===role);}if(actors.length&&actors.every(p=>s.actions[p.id]))s.deadline=Math.min(s.deadline,now+3000);}
function act(s,id,input,now=Date.now()){
 const p=member(s,id);if(!p.alive&&!(s.phase==='hunter'&&s.hunterQueue?.[0]===id))fail('Bạn đã bị loại.');if(input.phaseId!==s.phaseId)fail('Giai đoạn đã đổi. Hãy cập nhật phòng.',409);
 if(s.actions[id])fail('Bạn đã chốt lựa chọn trong giai đoạn này.',409);
 if(s.phase==='day'){if(input.skip!==true)fail('Bấm bỏ qua để kết thúc thảo luận sớm.');s.actions[id]={skip:true};shortenWhenComplete(s,now);return;}
 if(s.phase==='curse'){if(p.role!=='cursedWolf')fail('Chỉ Sói nguyền được lựa chọn.',403);const target=input.target==null?null:Number(input.target);if(target!==null){if(s.curseUsed)fail('Bạn đã dùng lời nguyền trong ván.');const t=member(s,target);if(!t.alive||isWolf(t)||target===s.pendingVictim)fail('Chọn người còn sống ngoài phe Sói, khác người bầy Sói chọn giết.');}s.pendingCurse=target;s.actions[id]={target};shortenWhenComplete(s,now);return;}
 if(s.phase==='witch'){
  if(p.role!=='witch')fail('Chỉ Phù thủy được dùng bình.',403);const save=input.save===true,poison=input.poison===null?null:Number(input.poison);
  if(save&&poison!==null)fail('Mỗi đêm chỉ được dùng một bình, không vừa cứu vừa giết.');if(save&&(!s.potions.save||s.pendingVictim===null))fail('Không thể dùng bình cứu.');if(poison!==null){if(!s.potions.poison||!member(s,poison).alive)fail('Không thể dùng bình độc.');}
  if(save)s.potions.save=false;if(poison!==null)s.potions.poison=false;s.actions[id]={save,poison};shortenWhenComplete(s,now);return;
 }
 if(s.phase==='cupid'){
  if(p.role!=='cupid')fail('Chỉ Cupid được ghép đôi.',403);
  if(s.day!==1)fail('Cupid chỉ ghép đôi đêm đầu.');if(!Array.isArray(input.lovers)||input.lovers.length!==2||input.lovers[0]===input.lovers[1]||input.lovers.some(id=>!Number.isInteger(id)||!member(s,id).alive))fail('Chọn hai người khác nhau để ghép đôi.');s.lovers=input.lovers;s.actions[id]={lovers:input.lovers};shortenWhenComplete(s,now);return;
 }
 if(!(s.phase==='vote'||s.phase==='night'&&isWolf(p)||s.phase==='guard'&&p.role==='guard'||s.phase==='seer'&&p.role==='seer'||s.phase==='hunter'&&s.hunterQueue?.[0]===id))fail('Chưa đến lượt hành động.');
 const target=input.target===null?null:Number(input.target);if(target!==null){const t=member(s,target);if(!t.alive)fail('Người này đã bị loại.');if(s.phase==='vote'&&target===id)fail('Không thể tự bỏ phiếu cho mình.');if(s.phase==='guard'&&p.role==='guard'&&p.previousGuard===target)fail('Không thể bảo vệ cùng người hai đêm liên tiếp.');}
 s.actions[id]={target};shortenWhenComplete(s,now);if(s.phase==='seer'&&p.role==='seer'&&target!==null){s.knowledge[id]??=[];s.knowledge[id].push({day:s.day,target,name:member(s,target).name,wolf:isWolf(member(s,target))});}
}
function channel(s,p){if(['lobby','ended'].includes(s.phase))return 'public';if(!p.alive)return 'dead';if(['announcement','reveal','cupid','curse','night','guard','seer','witch'].includes(s.phase))return isWolf(p)?'wolves':null;return 'public';}
function voiceChannel(s,p){return 'public';}
function snapshot(s,id,now=Date.now()){
 const p=member(s,id),ch=channel(s,p),voiceCh=voiceChannel(s,p),own=s.actions[id],lover=s.lovers?.includes(id)?s.players.find(q=>s.lovers.includes(q.id)&&q.id!==id):null;
 return {name:s.name,host:s.host,phase:s.phase,phaseId:s.phaseId,round:s.round,day:s.day,deadline:s.autoSkipAt&&now<s.autoSkipAt?s.autoSkipDisplayDeadline:s.deadline,serverTime:now,announcements:s.phase==='announcement'?s.announcements||[]:[],autoSkippedRole:s.autoSkippedRole||null,discussion:s.phase==='day'?{total:s.players.filter(q=>q.alive).length,skipped:s.players.filter(q=>q.alive&&s.actions[q.id]?.skip).length}:null,winner:s.winner,settings:s.settings,
  self:{id,cardRole:p.originalRole||p.role||null,cursedDay:p.cursedDay||null,loverInfo:lover?{id:lover.id,name:lover.name,faction:isWolf(lover)?'wolves':'village',cursedDay:lover.cursedDay||null}:null,canSpeak:!['announcement','cupid','curse','night','guard','seer','witch'].includes(s.phase),voiceChannel:voiceCh,hunterTurn:s.phase==='hunter'&&s.hunterQueue?.[0]===id,role:p.role||null,roleCard:p.role?roles[p.originalRole||p.role]:null,alive:p.alive,ready:p.ready,action:own||null,knowledge:s.knowledge[id]||[],channel:ch,lover:s.lovers?.includes(id)?s.players.find(q=>s.lovers.includes(q.id)&&q.id!==id)?.name:null,couple:p.role==='cupid'?s.lovers:undefined,curseVictim:p.role==='cursedWolf'&&s.phase==='curse'?s.pendingVictim:null,curseUsed:p.role==='cursedWolf'?s.curseUsed:undefined,potions:p.role==='witch'?s.potions:undefined,victim:p.role==='witch'&&s.phase==='witch'&&s.pendingVictim!==null?{id:s.pendingVictim,name:member(s,s.pendingVictim).name}:null},
  players:s.players.map(q=>({id:q.id,name:q.name,position:q.position||null,character:q.character??null,kicked:!!q.kicked,alive:q.alive,ready:q.ready,online:now-(q.lastSeen??now)<30000,role:s.phase==='ended'||(!q.alive&&s.settings.revealDeadRoles!==false)||q.id===id||(isWolf(p)&&isWolf(q))?q.role||null:null})),
  log:s.log,chat:s.chat.filter(m=>m.channel==='public'||m.channel===ch||s.phase==='ended').slice(-100),
  voicePeers:voiceCh?s.players.filter(q=>q.id!==id&&q.voiceUntil>now&&voiceChannel(s,q)===voiceCh).map(q=>q.id):[]};
}
function chat(s,id,content,now=Date.now()){const p=member(s,id),ch=channel(s,p);if(!ch)fail('Ban đêm chỉ Sói và người đã bị loại được trò chuyện.');if(typeof content!=='string'||!content.trim()||content.length>1000)fail('Tin nhắn cần từ 1 đến 1.000 ký tự.');s.chat.push({id:(s.chat.at(-1)?.id||0)+1,actor:id,name:p.name,content:content.trim(),channel:ch,at:now});s.chat=s.chat.slice(-200);}
module.exports={voiceChannel,configure,eliminate,endIfWon,roles,fail,member,create,start,advance,act,chat,snapshot,channel,plurality,isWolf};
