const {requireHost}=require('../services/boardRoomPermissions');
const presence=require('../services/boardPresence');
const r=require('express').Router(),db=require('../config/db'),game=require('../services/werewolf'),{randomUUID,randomInt,createHmac}=require('crypto'),{rateLimit}=require('express-rate-limit');
r.use(require('../middleware/authMiddleware').protect);
const run=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(e){if(e.status)return res.status(e.status).json({message:e.message});if(e.code==='22P02')return res.status(400).json({message:'Phòng không hợp lệ.'});next(e);}};
const limited=rateLimit({keyGenerator:req=>String(req.user.userId),message:{message:"Bạn thao tác quá nhanh. Chờ một chút rồi thử lại."},limit:40,windowMs:60000,standardHeaders:true,legacyHeaders:false});
async function persist(c,row){await c.query('UPDATE board_rooms SET state=$2,deadline=$3,updated_at=now() WHERE id=$1',[row.id,JSON.stringify(row.state),row.state.deadline?new Date(row.state.deadline):null]);}
async function room(req,work){return db.transaction(async c=>{const row=(await c.query('SELECT * FROM board_rooms WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!row)game.fail('Không tìm thấy phòng.',404);if(row.state.kickedIds?.includes(req.user.userId))game.fail('Bạn đã bị chủ phòng kick.',403);const before=JSON.stringify(row.state),p=game.member(row.state,req.user.userId);if(Date.now()-(p.lastSeen||0)>=10000)p.lastSeen=Date.now();const changed=game.advance(row.state)|presence.prune(row.state);const result=await work(row,c);if(JSON.stringify(row.state)!==before)await persist(c,row);return result??{...game.snapshot(row.state,req.user.userId),id:row.id,code:row.code};});}
r.get('/bootstrap',run(async(req,res)=>{const profile=(await db.query('SELECT id,name,avatar_url,plan FROM users WHERE id=$1',[req.user.userId])).rows[0];const rooms=(await db.query("SELECT id,code,state->>'name' AS name,state->>'phase' AS phase,jsonb_array_length(state->'players') AS count FROM board_rooms WHERE updated_at>now()-interval '24 hours' AND ((state->'players') @> $1::jsonb OR (state->>'phase' IN ('lobby','ended') AND state->'settings'->>'public'='true')) ORDER BY updated_at DESC LIMIT 40",[JSON.stringify([{id:req.user.userId}])])).rows;res.json({profile,rooms});}));
function nickname(value,fallback){if(value===undefined)return fallback;if(typeof value!=='string'||!value.trim()||value.trim().length>30||/[\x00-\x1f\x7f]/.test(value))game.fail('Biệt danh cần từ 1 đến 30 ký tự.');return value.trim();}
r.post('/rooms',limited,run(async(req,res)=>{const name=typeof req.body.name==='string'?req.body.name.trim():'';if(!name||name.length>70)game.fail('Tên phòng cần từ 1 đến 70 ký tự.');const profile=(await db.query('SELECT id,name,plan FROM users WHERE id=$1',[req.user.userId])).rows[0],id=randomUUID();const mode=require('../services/boardRoomMode').roomMode(req.body.mode,profile.plan);let code;for(let i=0;i<5;i++){code=String(randomInt(100000,1000000));try{await db.query('INSERT INTO board_rooms(id,code,state) VALUES($1,$2,$3)',[id,code,JSON.stringify(game.create({...profile,name:nickname(req.body.nickname,profile.name)},name,{...req.body,mode}))]);break;}catch(e){if(e.code!=='23505'||i===4)throw e;}}res.status(201).json({id,code});}));
r.post('/join',limited,run(async(req,res)=>{if(!/^\d{6}$/.test(req.body.code||''))game.fail('Mã phòng gồm 6 chữ số.');res.json(await db.transaction(async c=>{const row=(await c.query('SELECT * FROM board_rooms WHERE code=$1 FOR UPDATE',[req.body.code])).rows[0];if(!row)game.fail('Mã phòng không tồn tại.',404);const s=row.state;s.settings.capacity=14;if(s.kickedIds?.includes(req.user.userId))game.fail('Bạn đã bị kick khỏi phòng này.',403);if(!s.players.some(p=>p.id===req.user.userId)){if(!['lobby','ended'].includes(s.phase))game.fail('Ván đã bắt đầu, chỉ người trong phòng được vào lại.');if(s.players.length>=s.settings.capacity)game.fail('Phòng đã đủ người.');const p=(await c.query('SELECT id,name FROM users WHERE id=$1',[req.user.userId])).rows[0];s.players.push({...p,name:nickname(req.body.nickname,p.name),ready:false,alive:true,voiceUntil:0});await persist(c,row);}return {id:row.id,code:row.code};}));}));
r.post('/rooms/:id/move',run(async(req,res)=>res.json(await room(req,async row=>{const p=game.member(row.state,req.user.userId);if(!['lobby','ended','day','vote'].includes(row.state.phase)||!p.alive)game.fail('Chỉ di chuyển ở sân họp khi đang chờ hoặc ban ngày.');const {x,y,character,yaw,pitch}=req.body;if(!Number.isFinite(x)||!Number.isFinite(y)||x<.05||x>.95||y<.12||y>.9||!Number.isInteger(character)||character<0||character>13)game.fail('Vị trí hoặc nhân vật không hợp lệ.');if(Date.now()-(p.movedAt||0)<150)game.fail('Di chuyển quá nhanh.',429);if(yaw!==undefined&&(!Number.isFinite(yaw)||Math.abs(yaw)>1e6)||pitch!==undefined&&(!Number.isFinite(pitch)||Math.abs(pitch)>1.25))game.fail('Hướng nhìn không hợp lệ.');p.look={yaw:typeof yaw==='number'?Math.atan2(Math.sin(yaw),Math.cos(yaw)):0,pitch:typeof pitch==='number'?pitch:0};p.position={x,y};p.character=character;p.movedAt=Date.now();return {ok:true};}))));
r.get('/rooms/:id/positions',run(async(req,res)=>{const row=(await db.query('SELECT state FROM board_rooms WHERE id=$1',[req.params.id])).rows[0];if(!row)game.fail('Không tìm thấy phòng.',404);if(row.state.kickedIds?.includes(req.user.userId))game.fail('Bạn đã bị kick.',403);game.member(row.state,req.user.userId);res.json(row.state.players.map(p=>({id:p.id,position:p.position||null,character:p.character??null,look:p.look||null,movedAt:p.movedAt||0})));}));
r.get('/rooms/:id',run(async(req,res)=>res.json(await room(req,async()=>{}))));
r.post('/rooms/:id/ready',limited,run(async(req,res)=>res.json(await room(req,async row=>{if(!['lobby','ended'].includes(row.state.phase))game.fail('Ván đang diễn ra.');game.member(row.state,req.user.userId).ready=req.body.ready===true;}))));
r.post('/rooms/:id/settings',limited,run(async(req,res)=>res.json(await room(req,async row=>game.configure(row.state,req.user.userId,req.body.deck,req.body.timers,req.body.revealDeadRoles)))));
r.post('/rooms/:id/start',limited,run(async(req,res)=>res.json(await room(req,async row=>game.start(row.state,req.user.userId)))));
r.post('/rooms/:id/action',limited,run(async(req,res)=>res.json(await room(req,async row=>game.act(row.state,req.user.userId,req.body)))));
r.post('/rooms/:id/chat',limited,run(async(req,res)=>res.json(await room(req,async row=>game.chat(row.state,req.user.userId,req.body.content)))));
r.post('/rooms/:id/leave',limited,run(async(req,res)=>res.json(await room(req,async(row,c)=>{const s=row.state;if(!['lobby','ended'].includes(s.phase))game.fail('Ván đang diễn ra. Bạn có thể đóng màn hình và vào lại bằng mã phòng.');s.players=s.players.filter(p=>p.id!==req.user.userId);if(!s.players.length){await c.query('DELETE FROM board_rooms WHERE id=$1',[row.id]);return {ok:true};}if(s.host===req.user.userId)s.host=s.players[0].id;return {ok:true};}))));
r.post('/rooms/:id/disconnect',run(async(req,res)=>res.json(await room(req,async(row,c)=>{const s=row.state,p=game.member(s,req.user.userId);p.voiceUntil=0;if(req.body.explicit!==true)return {ok:true};p.lastSeen=0;p.ready=false;presence.prune(s);if(['lobby','ended'].includes(s.phase)){s.players=s.players.filter(q=>q.id!==p.id);if(!s.players.length){await c.query('DELETE FROM board_rooms WHERE id=$1',[row.id]);return {ok:true};}if(s.host===p.id)s.host=s.players[0].id;}return {ok:true};}))));
r.post('/rooms/:id/dissolve',limited,run(async(req,res)=>res.json(await room(req,async(row,c)=>{requireHost(row.state,req.user.userId);await c.query('DELETE FROM board_rooms WHERE id=$1',[row.id]);return {ok:true};}))));
r.post('/rooms/:id/players/:playerId/host',limited,run(async(req,res)=>res.json(await room(req,async row=>{requireHost(row.state,req.user.userId);const target=game.member(row.state,Number(req.params.playerId));if(target.kicked||Date.now()-(target.lastSeen??0)>=30000)game.fail('Người này không còn kết nối.');row.state.host=target.id;}))));
r.post('/rooms/:id/players/:playerId/kick',limited,run(async(req,res)=>res.json(await room(req,async row=>{const s=row.state;requireHost(s,req.user.userId);const target=game.member(s,Number(req.params.playerId));if(target.id===s.host)game.fail('Không thể kick chính mình.');s.kickedIds=[...new Set([...(s.kickedIds||[]),target.id])];target.voiceUntil=0;target.lastSeen=0;target.kicked=true;if(['lobby','ended'].includes(s.phase))s.players=s.players.filter(p=>p.id!==target.id);else{game.eliminate(s,target.id,'bị chủ phòng kick.',Date.now());game.endIfWon(s,Date.now());}}))));
r.get('/voice-config',run(async(req,res)=>{const iceServers=[{urls:'stun:stun.cloudflare.com:3478'}];if(process.env.BOARD_TURN_SECRET&&process.env.BOARD_TURN_URL){const username=Math.floor(Date.now()/1000+3600)+':'+req.user.userId;iceServers.push({urls:process.env.BOARD_TURN_URL.split(','),username,credential:createHmac('sha1',process.env.BOARD_TURN_SECRET).update(username).digest('base64')});}res.json({iceServers,relayConfigured:iceServers.length>1});}));
r.post('/rooms/:id/voice',limited,run(async(req,res)=>res.json(await room(req,async row=>{game.member(row.state,req.user.userId).voiceUntil=req.body.enabled===true?Date.now()+45000:0;}))));
r.post('/rooms/:id/signals',rateLimit({keyGenerator:req=>String(req.user.userId),message:{message:"Tín hiệu voice quá nhanh."},limit:400,windowMs:60000}),run(async(req,res)=>res.json(await room(req,async(row,c)=>{const s=row.state,from=game.member(s,req.user.userId),to=game.member(s,Number(req.body.to)),ch=game.voiceChannel(s,from);if(!ch||ch!==game.voiceChannel(s,to)||from.id===to.id||from.voiceUntil<Date.now()||to.voiceUntil<Date.now())game.fail('Kênh voice đã thay đổi.',409);const payload=req.body.payload;if(!payload||!['offer','answer','candidate'].includes(payload.type)||JSON.stringify(payload).length>20000)game.fail('Tín hiệu voice không hợp lệ.');await c.query('INSERT INTO board_signals(room_id,sender,recipient,phase_id,payload) VALUES($1,$2,$3,$4,$5)',[row.id,from.id,to.id,s.phaseId,JSON.stringify(payload)]);return {ok:true};}))));
r.get('/rooms/:id/signals',run(async(req,res)=>{const row=(await db.query('SELECT state FROM board_rooms WHERE id=$1',[req.params.id])).rows[0];if(!row)game.fail('Không tìm thấy phòng.',404);const s=row.state,p=game.member(s,req.user.userId),ch=game.voiceChannel(s,p),now=Date.now();if(s.kickedIds?.includes(p.id))game.fail('Bạn đã bị chủ phòng kick.',403);if(p.voiceUntil<=now)return res.json([]);const after=Number(req.query.after)||0;const rows=(await db.query("SELECT id,sender,payload FROM board_signals WHERE room_id=$1 AND recipient=$2 AND id>$3 AND created_at>now()-interval '60 seconds' ORDER BY id LIMIT 100",[req.params.id,p.id,after])).rows;res.json(rows.filter(m=>{const sender=s.players.find(q=>q.id===m.sender);return sender&&!sender.kicked&&sender.voiceUntil>now&&game.voiceChannel(s,sender)===ch;}));}));
module.exports=r;
module.exports.startScheduler=()=>{let busy=false;const timer=setInterval(async()=>{if(busy)return;busy=true;try{const due=(await db.query("SELECT id FROM board_rooms WHERE true ORDER BY updated_at DESC LIMIT 100")).rows;for(const {id} of due)await db.transaction(async c=>{const row=(await c.query('SELECT * FROM board_rooms WHERE id=$1 FOR UPDATE',[id])).rows[0];if(row){const changed=game.advance(row.state)|presence.prune(row.state);if(!row.state.players.length)await c.query('DELETE FROM board_rooms WHERE id=$1',[id]);else if(changed)await persist(c,row);}});await db.query("DELETE FROM board_signals WHERE created_at<now()-interval '2 minutes'");await db.query("DELETE FROM board_rooms WHERE updated_at<now()-interval '7 days'");}catch(e){console.error('Board scheduler failed',{code:e.code});}finally{busy=false;}},3000);timer.unref();return ()=>clearInterval(timer);};

