const r=require('express').Router(),db=require('../config/db');
r.use(require('../middleware/authMiddleware').protect);
const fail=(status,message)=>{throw Object.assign(Error(message),{status});};
const run=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(e){if(e.status)return res.status(e.status).json({message:e.message});if(e.code==='23505')return res.status(409).json({message:'Thành viên đã ở trong nhóm.'});next(e);}};
const text=(v,max=200)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,'Nội dung không hợp lệ.');return v.trim();};
async function space(id,user,c=db){const s=(await c.query('SELECT s.* FROM task_spaces s JOIN task_members m ON m.space_id=s.id WHERE s.id=$1 AND m.user_id=$2',[id,user])).rows[0];if(!s)fail(403,'Bạn không có quyền truy cập nhóm.');return s;}
async function item(id,user,c=db){const t=(await c.query('SELECT * FROM task_items WHERE id=$1',[id])).rows[0];if(!t)fail(404,'Không tìm thấy công việc.');if(t.space_id)await space(t.space_id,user,c);else if(t.owner_id!==user)fail(403,'Bạn không có quyền truy cập.');return t;}
function fields(body){const title=text(body.title),description=body.description||'';if(typeof description!=='string'||description.length>5000)fail(400,'Mô tả quá dài.');const status=body.status||'TODO',priority=body.priority||'NORMAL';if(!['TODO','DOING','DONE'].includes(status)||!['LOW','NORMAL','HIGH'].includes(priority))fail(400,'Trạng thái không hợp lệ.');const date=body.dueDate||null;if(date&&!/^\d{4}-\d{2}-\d{2}$/.test(date))fail(400,'Ngày không hợp lệ.');const checklist=body.checklist||[];if(!Array.isArray(checklist)||checklist.length>50)fail(400,'Checklist tối đa 50 mục.');return {title,description,status,priority,date,checklist:checklist.map(x=>({title:text(x.title),done:x.done===true}))};}
r.get('/bootstrap',run(async(req,res)=>{const id=req.user.userId;const spaces=(await db.query('SELECT s.* FROM task_spaces s JOIN task_members m ON m.space_id=s.id WHERE m.user_id=$1 ORDER BY s.id',[id])).rows;const habits=(await db.query("SELECT h.*,coalesce((SELECT json_agg(d.day ORDER BY d.day) FROM task_habit_days d WHERE d.habit_id=h.id),'[]') AS days FROM task_habits h WHERE h.user_id=$1 ORDER BY h.id",[id])).rows;const profile=(await db.query('SELECT id,name,email,avatar_url FROM users WHERE id=$1',[id])).rows[0];res.json({spaces,habits,profile});}));
r.post('/spaces',run(async(req,res)=>{res.status(201).json(await db.transaction(async c=>{const s=(await c.query('INSERT INTO task_spaces(owner_id,name) VALUES($1,$2) RETURNING *',[req.user.userId,text(req.body.name,100)])).rows[0];await c.query('INSERT INTO task_members VALUES($1,$2)',[s.id,req.user.userId]);return s;}));}));
r.get('/spaces/:id/members',run(async(req,res)=>{await space(req.params.id,req.user.userId);res.json((await db.query('SELECT u.id,u.name,u.email FROM task_members m JOIN users u ON u.id=m.user_id WHERE m.space_id=$1 ORDER BY u.id',[req.params.id])).rows);}));
r.post('/spaces/:id/members',run(async(req,res)=>{const s=await space(req.params.id,req.user.userId);if(s.owner_id!==req.user.userId)fail(403,'Chỉ chủ nhóm được thêm thành viên.');const user=(await db.query("SELECT id FROM users WHERE lower(email)=$1 AND is_active IS NOT FALSE AND role!='employee'",[text(req.body.email,255).toLowerCase()])).rows[0];if(!user)fail(404,'Không tìm thấy tài khoản Peacee1.');await db.query('INSERT INTO task_members VALUES($1,$2)',[s.id,user.id]);res.json({ok:true});}));
r.get('/items',run(async(req,res)=>{if(req.query.spaceId)await space(req.query.spaceId,req.user.userId);res.json((await db.query('SELECT t.*,u.name AS assignee_name FROM task_items t LEFT JOIN users u ON u.id=t.assignee_id WHERE ($1::integer IS NOT NULL AND t.space_id=$1) OR ($1::integer IS NULL AND t.space_id IS NULL AND t.owner_id=$2) ORDER BY t.id DESC LIMIT 500',[req.query.spaceId||null,req.user.userId])).rows);}));
async function save(req,res,update){const id=req.user.userId;let old;if(update)old=await item(req.params.id,id);const sid=update?old.space_id:(req.body?.spaceId||null);if(sid)await space(sid,id);const f=fields(req.body),assigned=req.body.assigneeId||null;if(assigned){if(sid){if(!(await db.query('SELECT 1 FROM task_members WHERE space_id=$1 AND user_id=$2',[sid,assigned])).rows.length)fail(400,'Người được giao chưa ở trong nhóm.');}else if(assigned!==id)fail(400,'Công việc cá nhân chỉ giao cho bạn.');}const args=[f.title,f.description,f.status,f.priority,f.date,assigned,JSON.stringify(f.checklist)];const sql=update?'UPDATE task_items SET title=$1,description=$2,status=$3,priority=$4,due_date=$5,assignee_id=$6,checklist=$7,updated_at=now() WHERE id=$8 RETURNING *':'INSERT INTO task_items(title,description,status,priority,due_date,assignee_id,checklist,owner_id,space_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *';res.json((await db.query(sql,update?[...args,old.id]:[...args,id,sid])).rows[0]);}
r.post('/items',run((req,res)=>save(req,res,false)));r.put('/items/:id',run((req,res)=>save(req,res,true)));
r.delete('/items/:id',run(async(req,res)=>{await item(req.params.id,req.user.userId);await db.query('DELETE FROM task_items WHERE id=$1',[req.params.id]);res.json({ok:true});}));
async function messageScope(req){if(req.query.taskId||req.body?.taskId){const t=await item(req.query.taskId||req.body?.taskId,req.user.userId);return {task:t.id,space:null};}const s=await space(req.query.spaceId||req.body?.spaceId,req.user.userId);return {task:null,space:s.id};}
r.get('/messages',run(async(req,res)=>{const s=await messageScope(req);res.json((await db.query('SELECT m.*,u.name FROM task_messages m JOIN users u ON u.id=m.actor_id WHERE (m.task_id=$1 OR ($1::integer IS NULL AND m.task_id IS NULL AND m.space_id=$2)) AND m.id>$3 ORDER BY m.id DESC LIMIT 100',[s.task,s.space,Number(req.query.after)||0])).rows.reverse());}));
r.post('/messages',require('express-rate-limit').rateLimit({limit:30,windowMs:60000}),run(async(req,res)=>{const s=await messageScope(req);res.status(201).json((await db.query('INSERT INTO task_messages(space_id,task_id,actor_id,content) VALUES($1,$2,$3,$4) RETURNING *',[s.space,s.task,req.user.userId,text(req.body.content,3000)])).rows[0]);}));
r.post('/habits',run(async(req,res)=>{res.json((await db.query('INSERT INTO task_habits(user_id,title) VALUES($1,$2) RETURNING *',[req.user.userId,text(req.body.title)])).rows[0]);}));
r.put('/habits/:id/day',run(async(req,res)=>{const date=req.body.day;if(!/^\d{4}-\d{2}-\d{2}$/.test(date||''))fail(400,'Ngày không hợp lệ.');if(!(await db.query('SELECT 1 FROM task_habits WHERE id=$1 AND user_id=$2',[req.params.id,req.user.userId])).rows.length)fail(403,'Không có quyền.');if(req.body.done===true)await db.query('INSERT INTO task_habit_days VALUES($1,$2) ON CONFLICT DO NOTHING',[req.params.id,date]);else await db.query('DELETE FROM task_habit_days WHERE habit_id=$1 AND day=$2',[req.params.id,date]);res.json({ok:true});}));
module.exports=r;
