CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    plan VARCHAR(50) DEFAULT 'normal',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('INCOME', 'EXPENSE')),
    amount BIGINT NOT NULL,
    category VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Dành cho trường hợp cập nhật bảng cũ (nếu có lỗi thì bỏ qua)
ALTER TABLE users ADD COLUMN IF NOT EXISTS plan VARCHAR(50) DEFAULT 'normal';
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS coin INTEGER DEFAULT 0;
ALTER TABLE users ALTER COLUMN coin SET DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_checkin_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS checkin_streak INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS salary VARCHAR(255) DEFAULT '15000000';
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INT DEFAULT 25;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(50) DEFAULT 'Nam';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_goal_initialized BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS custom_categories JSONB;

ALTER TABLE users ADD COLUMN IF NOT EXISTS monthly_budgets JSONB DEFAULT '{}'::jsonb;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_saving JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS investment_income NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS custom_normal_saving NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS custom_bank_saving_total NUMERIC;
ALTER TABLE users ADD COLUMN IF NOT EXISTS user_goal JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS qa_pos JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS budget_settings JSONB;
