const MODULES=['employees','products','inventory','tables','online_orders'];
const LEVELS=['STAFF','WAREHOUSE','MANAGER','FULL'];
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
function modules(value){if(!Array.isArray(value)||value.some(x=>!MODULES.includes(x))||new Set(value).size!==value.length)fail(400,'Module không hợp lệ.');if(value.includes('inventory')&&!value.includes('products'))fail(400,'Kho hàng cần module Sản phẩm & bán hàng.');if(value.includes('online_orders')&&!value.includes('products'))fail(400,'Đơn hàng online cần module Sản phẩm & bán hàng.');return value;}
function permissions(owner,level,enabled){const effective=level==='WAREHOUSE'&&!enabled.includes('inventory')?'STAFF':level;return {owner,staff:owner,reports:owner,configure:owner,catalog:owner||effective==='FULL',warehouse:owner||['WAREHOUSE','MANAGER','FULL'].includes(effective),income:true,expense:owner||effective!=='STAFF',approve:owner||['MANAGER','FULL'].includes(effective)};}
const integer=(v,min=1,max=1000000000000)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=max;
function text(value,max,required=false){if(typeof value!=='string'||value.length>max||(required&&!value.trim()))fail(400,'Thông tin không hợp lệ.');return value.trim();}
function orderInput(body,online){if(!Array.isArray(body.items)||!body.items.length||body.items.length>100||body.items.some(x=>!x||!integer(x.productId,1,2147483647)||!integer(x.quantity,1,1000000))||new Set(body.items.map(x=>x.productId)).size!==body.items.length)fail(400,'Sản phẩm hoặc số lượng không hợp lệ.');if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(body.requestId||''))fail(400,'Mã yêu cầu không hợp lệ.');if(!['CASH','TRANSFER',...(online?['COD']:[])].includes(body.paymentMethod))fail(400,'Chọn phương thức thanh toán.');if(online){text(body.recipient,100,true);text(body.address,500,true);if(typeof body.phone!=='string'||!/^\+?[0-9 ()-]{8,25}$/.test(body.phone))fail(400,'Nhập số điện thoại hợp lệ.');}if(!integer(body.shippingFee??0,0)||!integer(body.discount??0,0))fail(400,'Phí vận chuyển hoặc giảm giá không hợp lệ.');if(!online&&((body.shippingFee||0)!==0||(body.discount||0)!==0))fail(400,'Đơn tại quầy không có phí giao hàng.');return body;}
module.exports={MODULES,LEVELS,fail,modules,permissions,integer,text,orderInput};
