import * as Crypto from 'expo-crypto';
import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Pressable,View} from 'react-native';
import Feather from '@expo/vector-icons/Feather';
import {Text,useTranslate,languages} from './i18n';
import {monthLabel} from './localizedLabels';
import {Button,Card,Label,TransactionSheet,useTheme} from './ui';
import {useMobile} from '../App';
type Review={id:string;month:string;language:string;ledger:string;analysis:string;created_at:string};
export default function AIReviewCard(){
 const {api,month,language,finance}=useMobile(),c=useTheme(),t=useTranslate();const [open,setOpen]=useState(false),[closing,setClosing]=useState(false),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[history,setHistory]=useState<Review[]>([]),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[result,setResult]=useState<{key:string;text:string;token?:string;saved?:boolean}|null>(null);const pending=useRef(false),attempt=useRef<{key:string;requestId:string}|null>(null);const key=`${month}-${language}-${finance.data?.profile.finance_mode}`;const current=result?.key===key?result:null;
 const load=async(before?:string)=>{const {data}=await api<{items:Review[];nextCursor:string|null}>(`/ai/reviews${before?`?before=${before}`:''}`);setHistory(rows=>before?[...rows,...data.items]:data.items);setCursor(data.nextCursor);};
 useEffect(()=>{if(!open)return;let live=true;api<{items:Review[];nextCursor:string|null}>('/ai/reviews').then(({data})=>{if(live){setHistory(data.items);setCursor(data.nextCursor);}}).catch(failure=>{if(live)setError(failure.message);});return()=>{live=false;};},[open,api]);
 const generate=async()=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{if(attempt.current?.key!==key)attempt.current={key,requestId:Crypto.randomUUID()};const {data}=await api<{analysis:string;reviewToken?:string}>('/ai/analyze','POST',{month,language,requestId:attempt.current.requestId});attempt.current=null;setResult({key,text:data.analysis,token:data.reviewToken});await finance.refresh();}catch(failure){setError(failure instanceof Error?failure.message:'Không thể nhận xét lúc này. Vui lòng thử lại.');}finally{pending.current=false;setBusy(false);}};
 const save=async(close=false)=>{if(pending.current||!current?.token)return;pending.current=true;setBusy(true);setError('');try{await api('/ai/reviews','POST',{reviewToken:current.token});setResult(row=>row?{...row,saved:true}:row);await load();setConfirm(false);if(close)setClosing(true);}catch(failure){setError(failure instanceof Error?failure.message:'Không lưu được nhận xét.');}finally{pending.current=false;setBusy(false);}};
 const requestClose=()=>{if(current?.token&&!current.saved&&!closing){setConfirm(true);return false;}return true;};
 return <><Pressable accessibilityRole="button" accessibilityLabel={t('AI nhận xét')} onPress={()=>{setClosing(false);setConfirm(false);setOpen(true);}} style={{padding:20,borderRadius:18,backgroundColor:c.card,borderWidth:1,borderColor:c.border,flexDirection:'row',alignItems:'center',gap:14}}><Feather name="zap" size={24} color={c.primary}/><View style={{flex:1,gap:5}}><Label>AI nhận xét</Label><Label muted>Nhận xét thu chi của tháng đang xem</Label></View><Feather name="chevron-right" size={20} color={c.primary}/></Pressable>{open&&<TransactionSheet title="AI nhận xét" closing={closing} canClose={!busy} onBeforeClose={requestClose} onClose={()=>{setOpen(false);setResult(row=>row?.saved?row:null);}}>{confirm?<Card><Label large>Lưu nhận xét trước khi đóng?</Label>{!!error&&<Text accessibilityRole="alert" style={{color:c.expense}}>{error}</Text>}<Button title="Lưu và đóng" disabled={busy} onPress={()=>void save(true)}/><Button title="Không lưu" secondary disabled={busy} onPress={()=>{setResult(null);setConfirm(false);setClosing(true);}}/><Button title="Quay lại" secondary disabled={busy} onPress={()=>setConfirm(false)}/></Card>:<>
 <Label translateContent={false}>{monthLabel(Number(month.slice(5)),Number(month.slice(0,4)),language)}</Label><Label muted>{finance.data?.profile.finance_mode==='family'?'Sổ chung Gia đình':'Sổ Cá nhân'}</Label><Card><Label muted>Khi bấm nhận xét, tổng thu chi và danh mục của tháng này được gửi tới Google Gemini. Không gửi tên, email, ghi chú hoặc ảnh.</Label><Button title={busy?'Đang nhận xét…':current?.text?'Cập nhật nhận xét · 100 xu':'Nhận xét thu chi · 100 xu'} onPress={()=>void generate()} disabled={busy}/></Card>{busy&&<ActivityIndicator color={c.primary}/>} {!!error&&<Text accessibilityRole="alert" style={{color:c.expense}}>{error}</Text>}{!!current?.text&&<Card><Text translateContent={false} selectable style={{fontSize:15,lineHeight:25,color:c.text}}>{current.text}</Text>{!!current.token&&<Button title={current.saved?'Đã lưu nhận xét':'Lưu nhận xét'} disabled={busy||current.saved} onPress={()=>void save()}/>}</Card>}<Label muted>Nhận xét dựa trên các giao dịch đã ghi, không phải toàn bộ tình hình tài chính của bạn.</Label>
 <Label large>Nhận xét đã lưu</Label>{!history.length&&<Label muted>Chưa có nhận xét đã lưu.</Label>}{history.map(item=><Card key={item.id}><Label translateContent={false}>{monthLabel(Number(item.month.slice(5)),Number(item.month.slice(0,4)),language)} · {languages.find(row=>row.value===item.language)?.label||item.language}</Label><Label muted>{item.ledger==='family'?'Sổ chung Gia đình':'Sổ Cá nhân'}</Label><Text translateContent={false} selectable style={{color:c.text,fontSize:14,lineHeight:23}}>{item.analysis}</Text></Card>)}{!!cursor&&<Button title="Xem thêm" secondary disabled={busy} onPress={()=>void load(cursor).catch(failure=>setError(failure.message))}/>}</>}</TransactionSheet>}</>;
}
