import {Text} from './i18n';
import React,{useState} from 'react';
import {useDesktop} from './responsive';
import {Pressable,View} from 'react-native';
import {Card,Label,useTheme,styles,Choices} from './ui';
import {TransactionRow} from './FinanceViews';
import {money,dateLabel,today} from './format';
import type {Transaction} from './types';
export function calendarCells(year:number,month:number){const first=(new Date(Date.UTC(year,month-1,1)).getUTCDay()+6)%7;const total=new Date(Date.UTC(year,month,0)).getUTCDate();return Array.from({length:Math.ceil((first+total)/7)*7},(_,index)=>{const day=index-first+1;return day>0&&day<=total?`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`:null;});}
const compact=(value:number)=>value>=1e6?`${(value/1e6).toFixed(1)}tr`:value>=1000?`${Math.round(value/1000)}k`:String(value);
export default function CalendarScreen({transactions,year,month}:{transactions:Transaction[];year:number;month:number}){
 const available=[...new Set(transactions.map(tx=>tx.currency||'VND'))];const [chosen,setChosen]=useState('VND');const currency=available.includes(chosen)?chosen:available[0]||chosen;const chartTransactions=transactions.filter(tx=>(tx.currency||'VND')===currency);
 const desktop=useDesktop();const c=useTheme();const [selected,setSelected]=useState(today().startsWith(`${year}-${String(month).padStart(2,'0')}`)?today():`${year}-${String(month).padStart(2,'0')}-01`);const prefix=`${year}-${String(month).padStart(2,'0')}`;const date=selected.startsWith(prefix)?selected:prefix+'-01';const totals=new Map<string,{income:number;expense:number}>();for(const item of chartTransactions){const key=item.date.slice(0,10),sum=totals.get(key)||{income:0,expense:0};sum[item.type==='INCOME'?'income':'expense']+=Number(item.amount);totals.set(key,sum);}const items=transactions.filter(item=>item.date.slice(0,10)===date);
 return <><Label large>Lịch chi tiêu</Label><Choices value={currency} onChange={setChosen} items={(available.length?available:[currency]).map(value=>({value,label:value}))}/><View style={{flexDirection:desktop?'row':'column',gap:24,alignItems:desktop?'flex-start':undefined}}><Card style={desktop?{flex:1,minWidth:0}:undefined}><View style={{flexDirection:'row',marginBottom:6}}>{['T2','T3','T4','T5','T6','T7','CN'].map(day=><Text key={day} style={{width:'14.2857%',textAlign:'center',fontSize:desktop?13:10,color:c.muted}}>{day}</Text>)}</View><View style={{flexDirection:'row',flexWrap:'wrap'}}>{calendarCells(year,month).map((key,index)=>{const sum=key?totals.get(key):null;const active=key===date;return <Pressable key={key||`empty-${index}`} disabled={!key} accessibilityRole="button" accessibilityLabel={key?`${dateLabel(key)}, thu ${money(sum?.income||0,currency)}, chi ${money(sum?.expense||0,currency)}`:undefined} accessibilityState={{selected:active}} onPress={()=>key&&setSelected(key)} style={{width:'14.2857%',height:desktop?104:64,padding:2,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:active?c.primary:'transparent',gap:4}}><Text style={{fontSize:desktop?18:12,lineHeight:desktop?24:16,fontWeight:active?'800':'600',color:active?'white':key===today()?c.primary:c.text}}>{key?Number(key.slice(-2)):''}</Text>{sum?.income? <Text numberOfLines={1} style={{fontSize:desktop?15:10,lineHeight:desktop?20:12,fontWeight:'600',color:active?'#DFFFF1':c.income}}>+{compact(sum.income)}</Text>:null}{sum?.expense?<Text numberOfLines={1} style={{fontSize:desktop?15:10,lineHeight:desktop?20:12,fontWeight:'600',color:active?'#FFE8E4':c.expense}}>−{compact(sum.expense)}</Text>:null}</Pressable>;})}</View></Card><View style={{width:desktop?320:undefined,gap:16}}><View style={styles.row}><Label large>{dateLabel(date)}</Label><Label muted>{items.length} giao dịch</Label></View>{!items.length?<Card><Label muted>Chưa có giao dịch trong ngày này.</Label></Card>:items.map(item=><TransactionRow key={item.id} item={item}/>)} </View></View></>;
}


