import {groupedNumber} from './numberInput';
import AIReviewCard from './AIReviewCard';
import React,{useState} from 'react';
import {Pressable,ScrollView,View} from 'react-native';
import Feather from '@expo/vector-icons/Feather';
import Svg,{Path,Line} from 'react-native-svg';
import {Text} from './i18n';
import {Brand} from './brand';
import {Button,Card,Choices,Label,styles,useTheme} from './ui';
import {currencyTotals} from './format';
import {TransactionRow} from './FinanceViews';
import type {Profile,Summary,Transaction} from './types';
type Tab='home'|'analytics'|'calendar'|'profile';
type Action='family'|'goals'|'daily'|'notifications'|'appearance'|'language';
export function DesktopSidebar({tab,onTab,onAction,onLogout}:{tab:Tab;onTab:(tab:Tab)=>void;onAction:(action:Action)=>void;onLogout:()=>void}){
 const c=useTheme();const row=(key:string,title:string,icon:React.ComponentProps<typeof Feather>['name'],onPress:()=>void,active=false)=><Pressable key={key} accessibilityRole="button" accessibilityLabel={title} accessibilityState={{selected:active}} onPress={onPress} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:12,padding:13,borderRadius:12,backgroundColor:active?c.bg:'transparent',opacity:pressed?.7:1})}><Feather name={icon} size={18} color={active?c.primary:c.muted}/><Text style={{color:active?c.primary:c.text,fontSize:14,fontWeight:active?'700':'500'}}>{title}</Text></Pressable>;
 return <View style={{width:224,backgroundColor:c.card,borderRightWidth:1,borderColor:c.border,padding:20,gap:28}}><Brand/><ScrollView showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}><Label muted>QUẢN LÝ TÀI CHÍNH</Label>{([{key:'home',title:'Trang chủ',icon:'home'},{key:'analytics',title:'Phân tích',icon:'pie-chart'},{key:'calendar',title:'Lịch',icon:'calendar'},{key:'profile',title:'Hồ sơ',icon:'user'}] as const).map(item=>row(item.key,item.title,item.icon,()=>onTab(item.key),tab===item.key))}<View style={{height:16}}/><Label muted>CÀI ĐẶT CÁ NHÂN</Label>{([{key:'family',title:'Gia đình',icon:'users'},{key:'goals',title:'Mục tiêu tiết kiệm',icon:'target'},{key:'daily',title:'Điểm danh hằng ngày',icon:'gift'},{key:'notifications',title:'Thông báo',icon:'bell'},{key:'appearance',title:'Giao diện',icon:'sun'},{key:'language',title:'Ngôn ngữ',icon:'globe'}] as const).map(item=>row(item.key,item.title,item.icon,()=>onAction(item.key)))}</ScrollView><View style={{borderTopWidth:1,borderColor:c.border,paddingTop:12}}>{row('logout','Đăng xuất','log-out',onLogout)}</View></View>;
}
export function DesktopDashboard({profile,summary,transactions,onAdd,onHistory,onDaily,onGoals,onFamily,onCategories,month}:{month:string;profile:Profile|null;summary:Summary|null;transactions:Transaction[];onAdd:(type:'INCOME'|'EXPENSE')=>void;onHistory:()=>void;onDaily:()=>void;onGoals:()=>void;onFamily:()=>void;onCategories:()=>void}){
 const expenseOnly=profile?.expense_only!==false;transactions=transactions.filter(tx=>!expenseOnly||tx.type==='EXPENSE');const c=useTheme();const available=[...new Set(transactions.map(tx=>tx.currency||'VND'))];const [chosen,setChosen]=useState(profile?.currency||'VND');const currency=available.includes(chosen)?chosen:available[0]||chosen;const chartTransactions=transactions.filter(tx=>(tx.currency||'VND')===currency);
 const [year,monthNumber]=month.split('-').map(Number),dayCount=new Date(Date.UTC(year,monthNumber,0)).getUTCDate();const days=Array.from({length:dayCount},(_,i)=>chartTransactions.filter(tx=>Number(tx.date.slice(8,10))===i+1).reduce((sum,tx)=>sum+(expenseOnly||tx.type==='INCOME'?1:-1)*Number(tx.amount),0));let running=0;const values=days.map(value=>running+=value);const min=Math.min(0,...values),max=Math.max(1,...values),points=values.map((v,i)=>`${i*600/(dayCount-1)},${150-(v-min)/(max-min)*120}`);const path='M'+points.join(' L');
 return <View style={{gap:24}}><View style={styles.row}><View style={{gap:6}}><Label large>Trang chủ</Label></View></View>
 <View style={{flexDirection:'row',gap:20}}>{[{title:'Chênh lệch thu chi tháng này',value:currencyTotals(summary,'balance','month',profile?.currency),color:c.primary},{title:'Thu nhập',value:currencyTotals(summary,'income','month',profile?.currency),color:c.income},{title:'Chi tiêu',value:currencyTotals(summary,'expense','month',profile?.currency),color:c.expense}].filter(item=>!expenseOnly||item.title==='Chi tiêu').map(item=><View key={item.title} style={{flex:1,backgroundColor:c.card,borderWidth:1,borderColor:c.border,borderRadius:18,padding:22,gap:12}}><Label muted>{item.title}</Label><Text style={{color:item.color,fontSize:26,fontWeight:'800'}}>{item.value}</Text></View>)}</View>
 <Pressable accessibilityRole="button" accessibilityLabel="Thêm giao dịch" onPress={()=>onAdd('EXPENSE')} style={({pressed})=>({alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:12,backgroundColor:c.primary,borderRadius:14,paddingHorizontal:26,minHeight:54,boxShadow:'0px 4px 14px rgba(0,0,0,.15)',opacity:pressed?.8:1})}><Feather name="plus" size={24} color="white"/><Text style={{color:'white',fontSize:16,fontWeight:'700'}}>Thêm giao dịch</Text></Pressable>
 <View style={{flexDirection:'row',gap:24,alignItems:'flex-start'}}><View style={{flex:1,minWidth:0,gap:24}}><Card><Label large>{expenseOnly?'Phân tích chi tiêu':'Phân tích thu chi'}</Label><Choices items={(available.length?available:[currency]).map(value=>({value,label:value}))} value={currency} onChange={setChosen}/><Label muted>{expenseOnly?'Chi tiêu lũy kế trong tháng':'Chênh lệch thu chi tháng này'}</Label><Svg width="100%" height={190} viewBox="0 0 600 180" preserveAspectRatio="none" accessibilityLabel={expenseOnly?'Biểu đồ chi tiêu lũy kế theo ngày':'Biểu đồ thu chi lũy kế theo ngày'}><Line x1={0} y1={150} x2={600} y2={150} stroke={c.border}/><Path d={`${path} L600,170 L0,170 Z`} fill={c.primary} fillOpacity={.1}/><Path d={path} stroke={c.primary} strokeWidth={3} fill="none"/></Svg><View style={styles.row}><Label muted>01</Label><Label muted>15</Label><Label muted>{dayCount}</Label></View></Card><Card><View style={styles.row}><Label large>Giao dịch gần đây</Label><Pressable accessibilityRole="button" onPress={onHistory}><Text style={{color:c.primary}}>Xem tất cả →</Text></Pressable></View>{transactions.length?transactions.slice(0,6).map(item=><TransactionRow key={item.id} item={item}/>):<Label muted>{expenseOnly?'Chưa có khoản chi. Thêm khoản chi để bắt đầu.':'Chưa có giao dịch. Thêm khoản thu hoặc chi để bắt đầu.'}</Label>}</Card></View>
 <View style={{width:280,gap:20}}><AIReviewCard/><Card><Feather name="tag" size={24} color={c.primary}/><Label>Danh mục thu chi</Label><Label muted>Thêm hoặc sửa: 100 xu mỗi lần. Xoá danh mục miễn phí.</Label><Button title="Thêm danh mục" onPress={onCategories}/></Card><Card><Feather name="gift" size={24} color={c.primary}/><Label large>Điểm danh hằng ngày</Label><Label muted>ĐIỂM THƯỞNG</Label><Text style={{color:c.primary,fontSize:24,fontWeight:'700'}}>{groupedNumber(profile?.coin||0)} xu</Text><Button title="Điểm danh hằng ngày" onPress={onDaily}/></Card><Card><Feather name="target" size={24} color={c.primary}/><Label>Mục tiêu tiết kiệm</Label><Label muted>Xem tiến độ và cập nhật tiền đã dành</Label><Button title="Mục tiêu tiết kiệm" onPress={onGoals} secondary/></Card><Card><Feather name="users" size={24} color={c.primary}/><Label>{profile?.finance_mode==='family'?'Sổ chung Gia đình':'Sổ Cá nhân'}</Label><Label muted>Dữ liệu đồng bộ với Peacee1</Label><Button title="Gia đình" onPress={onFamily} secondary/></Card></View></View></View>;
}
