import CategoriesScreen from './CategoriesScreen';
import {categoryStyle} from './categoryStyle';
import {Pressable,View} from 'react-native';
import Feather from '@expo/vector-icons/Feather';
import {currencyAmountError} from './currency';
import {Text,useCategoryLabel,useTranslate} from './i18n';
import React,{useRef,useState} from 'react';
import {Button,Choices,Field,Label,TransactionSheet,useTheme} from './ui';
import {today,validDate} from './format';
import type {Api} from './api';
import type {Profile,Transaction} from './types';
export default function TransactionForm({type,profile,api,onClose,onSaved,transaction}:{type:'INCOME'|'EXPENSE';profile:Profile;transaction?:Transaction;api:Api;onClose:()=>void;onSaved:()=>Promise<void>}){
 const t=useTranslate(),[manage,setManage]=useState(false);const labelCategory=useCategoryLabel();const [kind,setKind]=useState(type); const c=useTheme(),currency=transaction?.currency||profile.currency||'VND',categories=profile.custom_categories.filter(item=>item.type===kind);if(transaction&&kind===transaction.type&&!categories.some(item=>item.name===transaction.category))categories.push({name:transaction.category,type:kind,color:'#9CA3AF'});const [amount,setAmount]=useState(transaction?String(Number(transaction.amount)):''),[category,setCategory]=useState(transaction?.category||categories[0]?.name||''),[date,setDate]=useState(transaction?.date.slice(0,10)||today()),[note,setNote]=useState(transaction?.description||''),[payment,setPayment]=useState<string>(transaction?.payment_method||'CASH'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[closing,setClosing]=useState(false);const pending=useRef(false);
 const submit=async()=>{if(pending.current||closing)return;const invalid=currencyAmountError(amount,currency);if(invalid||!categories.some(item=>item.name===category)||!validDate(date)){setError(invalid||(!categories.some(item=>item.name===category)?'Chọn danh mục.':'Nhập ngày hợp lệ theo dạng YYYY-MM-DD.'));return;}pending.current=true;setBusy(true);setError('');try{await api(transaction?`/transactions/${transaction.id}`:'/transactions',transaction?'PUT':'POST',{type:kind,amount:Number(amount),...(!transaction?{currency}:{}),category,date,description:note,...(profile.separate_personal_wallets?{paymentMethod:payment}:{})});await onSaved();setClosing(true);}catch(failure){setError(failure instanceof Error?failure.message:'Không lưu được giao dịch.');}finally{pending.current=false;setBusy(false);}};
 return <TransactionSheet closing={closing} canClose={!busy} title={transaction?'Sửa giao dịch':kind==='INCOME'?'Thêm khoản thu':'Thêm khoản chi'} onClose={()=>{if(!pending.current)onClose();}}><Choices value={kind} onChange={value=>{if(pending.current)return;const next=value as 'INCOME'|'EXPENSE';setKind(next);setCategory(profile.custom_categories.find(item=>item.type===next)?.name||'');setError('');}} items={[{value:'EXPENSE',label:'Khoản chi'},...(profile.expense_only===false||transaction?.type==='INCOME'?[{value:'INCOME',label:'Khoản thu'}]:[])]}/><Label muted>{profile.finance_mode==='family'?'Lưu vào sổ chung Gia đình':'Lưu vào sổ Cá nhân'}</Label><Field label={`Số tiền (${currency})`} value={amount} onChange={value=>setAmount(value.replace(/[^0-9.]/g,''))} numeric placeholder="50000"/><Label muted>Danh mục</Label><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{categories.map(item=>{const meta=categoryStyle(item.name,item.type,profile.custom_categories);return <Pressable key={item.name} accessibilityRole="button" accessibilityState={{selected:category===item.name}} onPress={()=>setCategory(item.name)} style={{flexDirection:'row',alignItems:'center',gap:7,padding:12,borderRadius:12,borderWidth:1,borderColor:category===item.name?meta.color:c.border,backgroundColor:category===item.name?meta.color+'20':c.card}}><Feather name={meta.icon} size={16} color={meta.color}/><Text translateContent={false} style={{color:c.text}}>{labelCategory(item.name)}</Text></Pressable>;})}<Pressable accessibilityRole="button" accessibilityLabel={t('Thêm danh mục')} onPress={()=>setManage(true)} style={{flexDirection:'row',alignItems:'center',gap:7,padding:12,borderRadius:12,borderWidth:1,borderStyle:'dashed',borderColor:c.primary}}><Feather name="plus" size={16} color={c.primary}/><Text style={{color:c.primary}}>Thêm danh mục</Text></Pressable></View>{manage&&<CategoriesScreen onClose={()=>setManage(false)}/>}<Field label="Ngày (YYYY-MM-DD)" value={date} onChange={setDate} placeholder="2026-10-02"/><Field label="Ghi chú" value={note} onChange={setNote}/>{profile.separate_personal_wallets&&<><Label muted>Nguồn tiền</Label><Choices value={payment} onChange={setPayment} items={[{value:'CASH',label:'Tiền mặt'},{value:'TRANSFER',label:'Tài khoản'}]}/></>}{!!error&&<Text accessibilityRole="alert" style={{color:c.expense}}>{error}</Text>}<Button title={busy?'Đang lưu…':'Lưu giao dịch'} onPress={submit} disabled={busy||closing}/></TransactionSheet>;
}




