import React,{useState} from 'react';
import {View,ImageBackground,useWindowDimensions} from 'react-native';
import Feather from '@expo/vector-icons/Feather';
import {Text} from './i18n';
import {Card,Choices,useTheme} from './ui';
function Label({children,muted=false,large=false}:{children:React.ReactNode;muted?:boolean;large?:boolean}){const c=useTheme();return <Text style={{color:muted?c.muted:c.text,fontSize:large?28:16,fontWeight:large?'700':'400',lineHeight:large?36:25}}>{children}</Text>;}
export const widgetActions=[{icon:'plus',title:'Thêm khoản chi nhanh',short:'Thêm khoản chi',description:'Mở app để ghi khoản chi chỉ với 1 chạm.'},{icon:'maximize',title:'Quét QR thanh toán',short:'Quét QR',description:'Mở camera để quét QR và giao dịch.'},{icon:'calendar',title:'Lịch chi tiêu',short:'Lịch',description:'Xem lịch và tổng hợp giao dịch theo ngày.'}] as const;
export function GuideIcon({name,size=52}:{name:React.ComponentProps<typeof Feather>['name'];size?:number}){const c=useTheme();return <View style={{width:size,height:size,borderRadius:size*.35,backgroundColor:c.primary+'14',alignItems:'center',justifyContent:'center'}}><Feather name={name} size={size*.48} color={c.primary}/></View>;}
export function WidgetFace({size='medium',compact=false}:{size?:string;compact?:boolean}){const c=useTheme();return <View testID={compact?undefined:'widget-preview'} style={{width:size==='small'?158:'100%',height:size==='large'?270:compact?140:180,borderRadius:24,padding:compact?14:18,backgroundColor:c.card,justifyContent:'space-between',boxShadow:'0px 8px 24px rgba(0,0,0,.12)'}}><View style={{flexDirection:'row',alignItems:'center',gap:7}}><Feather name="credit-card" color={c.primary} size={18}/><Text testID={compact?undefined:'widget-preview-brand'} translateContent={false} style={{color:c.primary,fontWeight:'800',fontSize:18}}>Peacee1</Text></View>{size==='large'&&<Label muted>Theo giao diện đang dùng</Label>}<View style={{flexDirection:size==='large'?'column':'row',gap:size==='large'?12:6}}>{widgetActions.filter((_,i)=>size!=='small'||i===0).map(a=><View key={a.icon} style={{flex:size==='large'?undefined:1,flexDirection:size==='large'?'row':'column',alignItems:size==='small'?'flex-start':'center',gap:8}}><GuideIcon name={a.icon} size={size==='large'?40:compact?42:66}/><Text style={{color:c.text,fontSize:compact?10:13,fontWeight:'600',textAlign:'center'}}>{a.short}</Text></View>)}</View></View>;}
export default function WidgetPicker(){const c=useTheme(),{width}=useWindowDimensions(),wide=width>=650;const [size,setSize]=useState('medium');return <Card style={{padding:wide?24:18,gap:22}}><View style={{flexDirection:'row',alignItems:'center',gap:14}}><GuideIcon name="eye"/><View style={{flex:1,gap:5}}><Label large>Xem trước trên màn hình chính</Label><Label muted>Chọn kích thước widget để xem trước cách hiển thị.</Label></View></View><View style={{flexDirection:wide?'row':'column',gap:24}}><View style={{flex:1,gap:20}}><Choices stretch value={size} onChange={setSize} items={[{value:'small',label:'Nhỏ'},{value:'medium',label:'Vừa'},{value:'large',label:'Lớn'}]}/><ImageBackground source={require('../assets/widget-home-wallpaper.png')} imageStyle={{borderRadius:35}} style={{borderRadius:42,borderWidth:7,borderColor:c.border,padding:17,minHeight:size==='large'?490:430,overflow:'hidden',gap:28}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text translateContent={false} style={{color:'white',fontWeight:'700'}}>9:41</Text><View style={{flexDirection:'row',gap:5}}><Feather name="bar-chart" color="white" size={16}/><Feather name="wifi" color="white" size={16}/><Feather name="battery" color="white" size={18}/></View></View><View style={{alignItems:'center',gap:9}}><WidgetFace size={size}/><Text translateContent={false} style={{color:'white',fontWeight:'600'}}>Peacee1</Text></View><View style={{marginTop:'auto',backgroundColor:'#FFFFFF40',borderRadius:24,padding:12,flexDirection:'row',justifyContent:'space-between'}}>{(['phone','compass','message-circle','music'] as const).map((icon,i)=><View key={icon} style={{backgroundColor:['#31CE65','#279CEB','#31CE65','#FF5476'][i],width:44,height:44,borderRadius:13,alignItems:'center',justifyContent:'center'}}><Feather name={icon} size={25} color="white"/></View>)}</View></ImageBackground></View><View style={{flex:wide?.8:undefined,backgroundColor:c.bg,borderRadius:24,padding:20,gap:24}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><GuideIcon name="info" size={34}/><Label large>Widget Peacee1</Label></View>{widgetActions.map(a=><View key={a.icon} style={{flexDirection:'row',gap:12}}><GuideIcon name={a.icon}/><View style={{flex:1,gap:7}}><Text style={{color:c.text,fontSize:18,fontWeight:'700'}}>{a.title}</Text><Label muted>{a.description}</Label></View></View>)}<Label muted>Widget tự đổi theo giao diện đang dùng. Chọn kích thước thật trong bảng thêm widget của iPhone.</Label></View></View></Card>;}
