import React,{useState} from 'react';
import {View} from 'react-native';
import Feather from '@expo/vector-icons/Feather';

import {Text} from './i18n';
import {Card,Label,Choices,useTheme} from './ui';
export default function WidgetPicker(){
 const c=useTheme();const [size,setSize]=useState('medium');
 return <><Card><Label large>Xem trước widget</Label><Label muted>Xem trước trên màn hình chính</Label><Choices value={size} onChange={setSize} items={[{value:'small',label:'Nhỏ'},{value:'medium',label:'Vừa'}]}/></Card>{(()=>{const ink=c.primary,bg=c.card,muted=c.muted,button=c.bg;return <View style={{borderWidth:1,borderColor:c.border,borderRadius:26,padding:14,gap:12}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Label>Theo giao diện đang dùng</Label><Feather name="check-circle" size={20} color={c.primary}/></View><View style={{backgroundColor:'#D8D7D0',borderRadius:24,padding:18,alignItems:'center'}}><View testID="widget-preview" style={{width:size==='small'?158:'100%',height:158,borderRadius:24,padding:18,backgroundColor:bg,justifyContent:'space-between',boxShadow:'0px 8px 18px rgba(0,0,0,.10)'}}><View style={{flexDirection:'row',alignItems:'center',gap:6}}><Feather name="credit-card" color={ink} size={17}/><Text testID="widget-preview-brand" translateContent={false} style={{color:ink,fontWeight:'800',fontSize:17}}>Peacee1</Text></View>{size==='small'?<><View style={{width:42,height:42,borderRadius:14,backgroundColor:button,alignItems:'center',justifyContent:'center'}}><Feather name="plus" size={26} color={ink}/></View><Text style={{color:ink,fontWeight:'700',fontSize:13}}>Thêm khoản chi</Text></>:<View style={{flexDirection:'row',gap:8}}>{([{icon:'plus',title:'Thêm khoản chi'},{icon:'maximize',title:'Quét QR thanh toán'},{icon:'calendar',title:'Lịch'}] as const).map(action=><View key={action.icon} style={{flex:1,alignItems:'center',gap:8}}><View style={{width:44,height:44,borderRadius:14,backgroundColor:button,alignItems:'center',justifyContent:'center'}}><Feather name={action.icon} size={22} color={ink}/></View><Text numberOfLines={2} style={{color:muted,fontSize:10,fontWeight:'600',textAlign:'center'}}>{action.title}</Text></View>)}</View>}</View></View></View>;})()}<Label muted>Widget tự đổi theo giao diện đang dùng. Chọn kích thước thật trong bảng thêm widget của iPhone.</Label></>;
}
