import WidgetPicker,{GuideIcon,WidgetFace,widgetActions} from './WidgetPicker';
import React from 'react';
import {Platform,View,Image,useWindowDimensions} from 'react-native';
import {Text} from './i18n';
import {Card,Sheet,useTheme} from './ui';
function Label({children,muted=false,large=false}:{children:React.ReactNode;muted?:boolean;large?:boolean}){const c=useTheme();return <Text style={{color:muted?c.muted:c.text,fontSize:large?28:16,fontWeight:large?'700':'400',lineHeight:large?36:25}}>{children}</Text>;}
const steps=[{icon:'download',title:'Cài đặt ứng dụng',body:'Cài bản Peacee1 có widget và mở app một lần.'},{icon:'grid',title:'Nhấn giữ màn hình chính',body:'Nhấn và giữ vùng trống trên màn hình chính.'},{icon:'plus-square',title:'Thêm widget',body:'Chọn Sửa → Thêm widget → tìm và chọn Peacee1.'},{icon:'layout',title:'Chọn kích thước',body:'Chọn kích thước nhỏ, vừa hoặc lớn rồi bấm Thêm widget.'}] as const;
export default function WidgetSetup({onClose}:{onClose:()=>void}){const c=useTheme(),{width}=useWindowDimensions(),wide=width>=650;
return <Sheet maxWidth={1040} title="Widget" onClose={onClose}>{Platform.OS==='android'?<Card><Label large>Thêm widget trên Android</Label><Label>1. Cài bản Peacee1 có widget và mở app một lần.</Label><Label>2. Nhấn giữ vùng trống trên màn hình chính → Widget → tìm Peacee1.</Label><Label>3. Nhấn giữ widget Peacee1 và kéo ra màn hình chính.</Label><Label muted>Widget Android đang được phát triển. Nếu chưa thấy Peacee1 trong danh sách, bản app hiện tại chưa có widget Android.</Label></Card>:<><Card style={{padding:28,overflow:'hidden'}}><View style={{flexDirection:wide?'row':'column',gap:24}}><View style={{flex:1,gap:18}}><View style={{flexDirection:'row',alignItems:'center',gap:14}}><GuideIcon name="credit-card" size={60}/><View style={{flex:1,gap:6}}><Text style={{color:c.primary,fontWeight:'800',fontSize:13}}>WIDGET iPHONE</Text><Label large>Xem trước widget iPhone</Label></View></View><Label muted>Đây là bản xem trước giao diện và hướng dẫn. Để thêm widget vào màn hình chính, cần cài app Peacee1 trên iPhone.</Label><View style={{flexDirection:wide?'row':'column',gap:12}}>{widgetActions.map(a=><View key={a.icon} style={{flex:wide?1:undefined,flexDirection:'row',alignItems:'center',gap:10}}><GuideIcon name={a.icon} size={50}/><Text style={{flex:1,color:c.muted,fontSize:14,lineHeight:21}}>{a.title}</Text></View>)}</View></View>{wide&&<View style={{width:300,height:295,marginBottom:-24,alignSelf:'flex-end'}}><Image source={require('../assets/widget-iphone-frame.png')} style={{position:'absolute',width:300,height:400,top:0}} resizeMode="stretch"/><View style={{position:'absolute',left:28,right:28,top:96,transform:[{rotate:'-3deg'}]}}><WidgetFace compact/></View></View>}</View></Card><WidgetPicker/><Card style={{padding:24,gap:22}}><View style={{flexDirection:'row',alignItems:'center',gap:14}}><GuideIcon name="settings"/><View style={{flex:1,gap:6}}><Label large>Hướng dẫn thêm widget trên iPhone</Label><Label muted>Thực hiện theo các bước sau để thêm widget Peacee1:</Label></View></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}>{steps.map((step,index)=><View key={step.title} style={{width:width>=1000?'23%':wide?'47%':'100%',padding:16,borderWidth:1,borderColor:c.border,borderRadius:20,gap:14}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View style={{width:30,height:30,borderRadius:15,backgroundColor:c.primary,justifyContent:'center',alignItems:'center'}}><Text translateContent={false} style={{color:'white',fontWeight:'700'}}>{index+1}</Text></View></View><View style={{width:160,height:190,alignSelf:'center',overflow:'hidden'}}><Image source={require('../assets/widget-setup-steps.png')} resizeMode="stretch" style={{width:640,height:214,position:'absolute',left:-index*160,top:-12}}/></View><Text style={{color:c.text,fontSize:15,fontWeight:'700'}}>{step.title}</Text><Label muted>{step.body}</Label></View>)}</View></Card></>}</Sheet>;}
