const $=id=>document.getElementById(id);
const tracks=[['Kick','#b6ef76'],['Snare','#ffb16b'],['Clap','#ed839d'],['Hi-hat','#8ed5dc'],['Open hat','#b8a0ee'],['Bass','#e5cc7e']].map(([name,color])=>({name,color,steps:Array(16).fill(false),volume:.75,mute:false}));
let context,master,playing=false,timer,nextTime=0,step=0,generation=0;
const bpm=()=>Math.max(40,Math.min(240,Number($('bpm').value)||120));
function status(message){$('status').textContent=message;}
function initAudio(){if(!context){context=new AudioContext();master=context.createGain();master.gain.value=Number($('master').value)/100;master.connect(context.destination);}return context.resume();}
function sound(ctx,out,index,time,level){const gain=ctx.createGain();gain.connect(out);const peak=Math.max(.001,level*.38);gain.gain.setValueAtTime(peak,time);let duration=.2,source;
if(index===0||index===5){source=ctx.createOscillator();source.type=index===0?'sine':'triangle';duration=index===0?.45:.28;source.frequency.setValueAtTime(index===0?145:65.41,time);source.frequency.exponentialRampToValueAtTime(index===0?42:55,time+(index===0?.12:.23));source.connect(gain);}else{duration=[0,.18,.14,.055,.3][index];const buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;source=ctx.createBufferSource();source.buffer=buffer;const filter=ctx.createBiquadFilter();filter.type=index>2?'highpass':'bandpass';filter.frequency.value=index>2?6500:1700;source.connect(filter);filter.connect(gain);if(index===2){gain.gain.setValueAtTime(peak*.25,time);gain.gain.setValueAtTime(peak,time+.012);gain.gain.setValueAtTime(peak*.3,time+.02);gain.gain.setValueAtTime(peak,time+.028);}}
gain.gain.exponentialRampToValueAtTime(.0001,time+duration);source.start(time);source.stop(time+duration+.01);source.onended=()=>{source.disconnect();gain.disconnect();};}
function draw(){const rack=$('rack');rack.replaceChildren();const numbers=document.createElement('div');numbers.className='row numbers';numbers.innerHTML='<span style="text-align:left">INSTRUMENT / VOLUME</span>'+Array.from({length:16},(_,i)=>`<span class="${i%4===0?'groupnum':''}">${String(i+1).padStart(2,'0')}</span>`).join('');rack.append(numbers);tracks.forEach((track,index)=>{const row=document.createElement('div');row.className='row';row.style.setProperty('--color',track.color);const label=document.createElement('div');label.className='instrument';const mute=document.createElement('button');mute.className='mute'+(track.mute?' muted':'');mute.textContent='●';mute.setAttribute('aria-label',`Bật/tắt ${track.name}`);mute.setAttribute('aria-pressed',String(!track.mute));mute.onclick=()=>{track.mute=!track.mute;draw();};const name=document.createElement('button');name.className='sound';name.textContent=track.name;name.onclick=async()=>{try{await initAudio();master.gain.setValueAtTime(Number($("master").value)/100,context.currentTime);sound(context,master,index,context.currentTime,track.volume);}catch{status('Trình duyệt không mở được âm thanh. Hãy thử Chrome hoặc Edge.');}};const volume=document.createElement('input');volume.type='range';volume.min=0;volume.max=100;volume.value=track.volume*100;volume.setAttribute('aria-label',`Âm lượng ${track.name}`);volume.oninput=()=>track.volume=Number(volume.value)/100;label.append(mute,name,volume);row.append(label);track.steps.forEach((on,s)=>{const button=document.createElement('button');button.className='step'+(Math.floor(s/4)%2?' group':'')+(on?' on':'');button.dataset.step=s;button.setAttribute('aria-label',`${track.name}, bước ${s+1}`);button.setAttribute('aria-pressed',String(on));button.onclick=()=>{track.steps[s]=!track.steps[s];button.classList.toggle('on',track.steps[s]);button.setAttribute('aria-pressed',String(track.steps[s]));count();};row.append(button);});rack.append(row);});count();}
function count(){$('count').textContent=tracks.reduce((n,t)=>n+t.steps.filter(Boolean).length,0);}
function mark(s){window.Melody?.mark(s);document.querySelectorAll('.step').forEach(b=>b.classList.toggle('current',Number(b.dataset.step)===s));$('position').textContent=`01 : ${String(s+1).padStart(2,'0')}`;}
function schedule(){while(nextTime<context.currentTime+.1){const current=step,token=generation;tracks.forEach((t,i)=>{if(t.steps[current]&&!t.mute)sound(context,master,i,nextTime,t.volume);});window.Melody?.schedule(context,master,current,nextTime);setTimeout(()=>{if(playing&&generation===token)mark(current);},Math.max(0,(nextTime-context.currentTime)*1000));const swing=Number($('swing').value)/100;nextTime+=60/bpm()/4*(current%2?1-swing:1+swing);step=(step+1)%16;}}
function pause(reset=false){playing=false;generation++;clearInterval(timer);if(master&&context){master.gain.cancelScheduledValues(context.currentTime);master.gain.setValueAtTime(0,context.currentTime);} $('play').innerHTML='▶ <span>Phát beat</span>';if(reset){window.Melody?.mark(-1);step=0;document.querySelectorAll('.current').forEach(b=>b.classList.remove('current'));$('position').textContent='01 : 01';}}
async function toggle(){if(playing){pause();return;}try{await initAudio();master.gain.setValueAtTime(Number($('master').value)/100,context.currentTime);playing=true;generation++;nextTime=context.currentTime+.03;$('play').innerHTML='Ⅱ <span>Tạm dừng</span>';schedule();timer=setInterval(schedule,25);status('Đang phát · Nhấn Space để tạm dừng');}catch{status('Không thể phát âm thanh trên trình duyệt này.');}}
function preset(type){pause(true);tracks.forEach(t=>t.steps.fill(false));const patterns={house:[[0,4,8,12],[4,12],[4,12],[0,2,4,6,8,10,12,14],[2,6,10,14],[0,3,6,8,11,14]],hiphop:[[0,6,8,11],[4,12],[],[0,2,4,6,8,10,12,14],[14],[0,6,8,11]],trap:[[0,7,10],[4,12],[12],[0,2,3,4,6,8,10,11,12,14,15],[6,14],[0,7,10,14]]};if(patterns[type])patterns[type].forEach((p,i)=>p.forEach(s=>tracks[i].steps[s]=true));$('bpm').value={house:120,hiphop:90,trap:140}[type]||120;draw();status(type==='empty'?'Bắt đầu một beat mới.':'Mẫu beat đã sẵn sàng. Bạn có thể chỉnh từng ô.');}
$('play').onclick=toggle;$('stop').onclick=()=>pause(true);$('preset').onchange=e=>preset(e.target.value);$('clear').onclick=()=>preset('empty');$('bpm').onchange=()=>$('bpm').value=bpm();$('swing').oninput=()=>$('swingval').value=$('swing').value+'%';$('master').oninput=()=>{$('masterval').value=$('master').value+'%';if(master&&playing)master.gain.setTargetAtTime(Number($('master').value)/100,context.currentTime,.01);};document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();toggle();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){pause(true);status('Đã dừng phát khi chuyển tab.');}});
$('export').onclick=async()=>{const button=$('export');button.disabled=true;status('Đang xuất 4 vòng beat thành WAV…');try{const rate=44100,beat=60/bpm()/4,ctx=new OfflineAudioContext(1,Math.ceil((beat*64+.5)*rate),rate),out=ctx.createGain();out.gain.value=Number($('master').value)/100;out.connect(ctx.destination);let time=0;for(let s=0;s<64;s++){tracks.forEach((t,i)=>{if(t.steps[s%16]&&!t.mute)sound(ctx,out,i,time,t.volume);});window.Melody?.schedule(ctx,out,s%16,time,bpm(),Number($("swing").value));time+=beat*(s%2?1-Number($('swing').value)/100:1+Number($('swing').value)/100);}const rendered=await ctx.startRendering(),samples=rendered.getChannelData(0),buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);const str=(offset,value)=>{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i));};str(0,'RIFF');view.setUint32(4,36+samples.length*2,true);str(8,'WAVE');str(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,samples.length*2,true);samples.forEach((value,i)=>view.setInt16(44+i*2,Math.max(-1,Math.min(1,value))*32767,true));const url=URL.createObjectURL(new Blob([buffer],{type:'audio/wav'})),a=document.createElement('a');a.href=url;a.download=`peacee1-${bpm()}bpm.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);status('Đã xuất WAV · 4 vòng beat, 44.1 kHz.');}catch{status('Xuất WAV chưa thành công. Hãy thử lại trên Chrome hoặc Edge.');}finally{button.disabled=false;}};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_beat',description:'Đặt BPM và các bước nhịp, cập nhật sequencer đang hiển thị.',inputSchema:{type:'object',properties:{bpm:{type:'number',minimum:40,maximum:240},tracks:{type:'array',items:{type:'object',properties:{index:{type:'integer',minimum:0,maximum:5},steps:{type:'array',items:{type:'integer',minimum:0,maximum:15}}},required:['index','steps'],additionalProperties:false}}},additionalProperties:false},execute(input){if(!input||typeof input!=='object'||(input.bpm!==undefined&&(!Number.isFinite(input.bpm)||input.bpm<40||input.bpm>240))||(input.tracks!==undefined&&(!Array.isArray(input.tracks)||input.tracks.some(t=>!t||!Number.isInteger(t.index)||t.index<0||t.index>5||!Array.isArray(t.steps)||t.steps.some(s=>!Number.isInteger(s)||s<0||s>15)))))throw Error('Cấu hình beat không hợp lệ');if(input.bpm!==undefined)$('bpm').value=input.bpm;if(input.tracks)input.tracks.forEach(t=>tracks[t.index].steps=Array.from({length:16},(_,s)=>t.steps.includes(s)));draw();return{bpm:bpm(),enabledSteps:tracks.map(t=>t.steps.flatMap((on,i)=>on?[i]:[]))};}})).catch(()=>{});}catch{}}
preset('house');
