let projectRevision=0,projectLoaded=false,isDirty=false,currentProjectId=null,projectList=[],projectBusy=false;
const editor=document.querySelector('main');editor.inert=true;editor.classList.add('auth-pending');
function projectChanged(){if(!projectLoaded||projectBusy)return;isDirty=true;$('save-state').textContent='Có thay đổi chưa lưu';}
window.projectChanged=projectChanged;
editor.addEventListener('input',event=>{if(event.target.id!=='project-select')projectChanged();});editor.addEventListener('change',event=>{if(event.target.id!=='project-select')projectChanged();});editor.addEventListener('click',event=>{if(event.target.closest('.step,.mute,#clear,#preset'))projectChanged();});
function readProject(){return{name:$('project-name').value.trim()||'Beat của tôi',bpm:bpm(),swing:Number($('swing').value),master:Number($('master').value),tracks:tracks.map(({steps,volume,mute})=>({steps:[...steps],volume,mute})),melody:Melody.read()};}
function restoreProject(project){pause(true);$('project-name').value=project.name;$('bpm').value=project.bpm;$('swing').value=project.swing;$('swingval').value=project.swing+'%';$('master').value=project.master;$('masterval').value=project.master+'%';project.tracks.forEach((track,index)=>Object.assign(tracks[index],track));draw();Melody.load(project.melody);$('preset').value='empty';}
function login(){pause(true);editor.inert=true;editor.classList.add('auth-pending');location.replace('https://peacee1.io.vn/login?returnTo='+encodeURIComponent('https://beatmaker.peacee1.io.vn/'));}
async function api(path,options={}){const response=await fetch('/api/'+path,{credentials:'same-origin',...options});if(response.status===401){login();throw Error('Vui lòng đăng nhập.');}const data=await response.json();if(!response.ok)throw Error(data.message||'Không thể kết nối máy chủ.');return data;}
function setBusy(busy){projectBusy=busy;editor.inert=busy;$('save-project').disabled=busy;$('new-project').disabled=busy;$('project-select').disabled=busy;}
function renderList(){$('project-select').replaceChildren();projectList.forEach(project=>{const option=document.createElement('option');option.value=String(project.id);option.textContent=project.name;$('project-select').append(option);});$('project-select').value=String(currentProjectId);}
function applyProject(data){currentProjectId=String(data.id);projectRevision=data.revision;restoreProject(data.project);isDirty=false;renderList();$('save-state').textContent='Đã tải dự án';}
function allowSwitch(){return !isDirty||confirm('Dự án có thay đổi chưa lưu. Tiếp tục và bỏ các thay đổi này?');}
async function createProject(initial=false){
 if(projectBusy||(!initial&&!allowSwitch()))return;
 const name=initial?'Beat của tôi':prompt('Tên dự án mới:','Beat mới');if(name===null)return;if(!name.trim()||name.trim().length>80){status('Tên dự án cần từ 1 đến 80 ký tự.');return;}
 setBusy(true);try{const project={name:name.trim(),bpm:120,swing:0,master:70,tracks:tracks.map(()=>({steps:Array(16).fill(false),mute:false,volume:.75})),melody:{voice:'triangle',volume:.45,mute:false,notes:[]}};const data=await api('beatmaker/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project})});projectList.unshift({id:data.id,name:data.project.name});applyProject(data);status('Đã tạo dự án mới. Drum và melody đã sẵn sàng để bạn viết.');}catch(error){status(error.message);if(initial)throw error;}finally{setBusy(false);}
}
$('new-project').onclick=()=>createProject();
$('project-select').onchange=async event=>{const id=event.target.value;if(projectBusy||!allowSwitch()){$('project-select').value=currentProjectId;return;}setBusy(true);try{applyProject(await api('beatmaker/projects/'+encodeURIComponent(id)));status('Đã mở dự án của bạn.');}catch(error){$('project-select').value=currentProjectId;status(error.message);}finally{setBusy(false);}};
$('save-project').onclick=async()=>{if(projectBusy||!currentProjectId)return;setBusy(true);try{const project=readProject();const result=await api('beatmaker/projects/'+encodeURIComponent(currentProjectId),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({project,revision:projectRevision})});projectRevision=result.revision;isDirty=false;const item=projectList.find(item=>String(item.id)===currentProjectId);if(item)item.name=project.name;renderList();$('save-state').textContent='Đã lưu dự án';status('Dự án đã lưu riêng cho tài khoản của bạn.');}catch(error){$('save-state').textContent='Chưa lưu được';status(error.message);}finally{setBusy(false);}};
async function loadProject(){try{const session=await api('auth/session');$('account-name').textContent=session.user.name;projectList=await api('beatmaker/projects');if(projectList.length)applyProject(await api('beatmaker/projects/'+projectList[0].id));else await createProject(true);projectLoaded=true;editor.inert=false;editor.classList.remove('auth-pending');$('auth-state').hidden=true;}catch(error){editor.inert=true;editor.classList.add('auth-pending');$('auth-state').textContent=error.message+' Tải lại trang để thử lại.';}}
window.addEventListener('beforeunload',event=>{if(isDirty){event.preventDefault();event.returnValue='';}});
loadProject();
