server {
    listen 80;
    server_name drums.peacee1.io.vn;
    root /usr/share/nginx/peacee1-drums;
    index index.html;
    location / { try_files $uri $uri/ =404; add_header Cache-Control "no-cache"; }
}
